// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/alias"
	"naust/daemon/internal/store/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AliasCreate is the builder for creating a Alias entity.
type AliasCreate struct {
	config
	mutation *AliasMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSource sets the "source" field.
func (_c *AliasCreate) SetSource(v string) *AliasCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetDestinations sets the "destinations" field.
func (_c *AliasCreate) SetDestinations(v []string) *AliasCreate {
	_c.mutation.SetDestinations(v)
	return _c
}

// SetPermittedSenders sets the "permitted_senders" field.
func (_c *AliasCreate) SetPermittedSenders(v []string) *AliasCreate {
	_c.mutation.SetPermittedSenders(v)
	return _c
}

// SetAuto sets the "auto" field.
func (_c *AliasCreate) SetAuto(v bool) *AliasCreate {
	_c.mutation.SetAuto(v)
	return _c
}

// SetNillableAuto sets the "auto" field if the given value is not nil.
func (_c *AliasCreate) SetNillableAuto(v *bool) *AliasCreate {
	if v != nil {
		_c.SetAuto(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AliasCreate) SetCreatedAt(v time.Time) *AliasCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AliasCreate) SetNillableCreatedAt(v *time.Time) *AliasCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_c *AliasCreate) SetTenantID(id int) *AliasCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *AliasCreate) SetTenant(v *Tenant) *AliasCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the AliasMutation object of the builder.
func (_c *AliasCreate) Mutation() *AliasMutation {
	return _c.mutation
}

// Save creates the Alias in the database.
func (_c *AliasCreate) Save(ctx context.Context) (*Alias, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AliasCreate) SaveX(ctx context.Context) *Alias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AliasCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AliasCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AliasCreate) defaults() {
	if _, ok := _c.mutation.Auto(); !ok {
		v := alias.DefaultAuto
		_c.mutation.SetAuto(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := alias.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AliasCreate) check() error {
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Alias.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := alias.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Alias.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Destinations(); !ok {
		return &ValidationError{Name: "destinations", err: errors.New(`ent: missing required field "Alias.destinations"`)}
	}
	if _, ok := _c.mutation.Auto(); !ok {
		return &ValidationError{Name: "auto", err: errors.New(`ent: missing required field "Alias.auto"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Alias.created_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Alias.tenant"`)}
	}
	return nil
}

func (_c *AliasCreate) sqlSave(ctx context.Context) (*Alias, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AliasCreate) createSpec() (*Alias, *sqlgraph.CreateSpec) {
	var (
		_node = &Alias{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(alias.Table, sqlgraph.NewFieldSpec(alias.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(alias.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Destinations(); ok {
		_spec.SetField(alias.FieldDestinations, field.TypeJSON, value)
		_node.Destinations = value
	}
	if value, ok := _c.mutation.PermittedSenders(); ok {
		_spec.SetField(alias.FieldPermittedSenders, field.TypeJSON, value)
		_node.PermittedSenders = value
	}
	if value, ok := _c.mutation.Auto(); ok {
		_spec.SetField(alias.FieldAuto, field.TypeBool, value)
		_node.Auto = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(alias.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alias.TenantTable,
			Columns: []string{alias.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_aliases = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Alias.Create().
//		SetSource(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AliasUpsert) {
//			SetSource(v+v).
//		}).
//		Exec(ctx)
func (_c *AliasCreate) OnConflict(opts ...sql.ConflictOption) *AliasUpsertOne {
	_c.conflict = opts
	return &AliasUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Alias.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AliasCreate) OnConflictColumns(columns ...string) *AliasUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AliasUpsertOne{
		create: _c,
	}
}

type (
	// AliasUpsertOne is the builder for "upsert"-ing
	//  one Alias node.
	AliasUpsertOne struct {
		create *AliasCreate
	}

	// AliasUpsert is the "OnConflict" setter.
	AliasUpsert struct {
		*sql.UpdateSet
	}
)

// SetSource sets the "source" field.
func (u *AliasUpsert) SetSource(v string) *AliasUpsert {
	u.Set(alias.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AliasUpsert) UpdateSource() *AliasUpsert {
	u.SetExcluded(alias.FieldSource)
	return u
}

// SetDestinations sets the "destinations" field.
func (u *AliasUpsert) SetDestinations(v []string) *AliasUpsert {
	u.Set(alias.FieldDestinations, v)
	return u
}

// UpdateDestinations sets the "destinations" field to the value that was provided on create.
func (u *AliasUpsert) UpdateDestinations() *AliasUpsert {
	u.SetExcluded(alias.FieldDestinations)
	return u
}

// SetPermittedSenders sets the "permitted_senders" field.
func (u *AliasUpsert) SetPermittedSenders(v []string) *AliasUpsert {
	u.Set(alias.FieldPermittedSenders, v)
	return u
}

// UpdatePermittedSenders sets the "permitted_senders" field to the value that was provided on create.
func (u *AliasUpsert) UpdatePermittedSenders() *AliasUpsert {
	u.SetExcluded(alias.FieldPermittedSenders)
	return u
}

// ClearPermittedSenders clears the value of the "permitted_senders" field.
func (u *AliasUpsert) ClearPermittedSenders() *AliasUpsert {
	u.SetNull(alias.FieldPermittedSenders)
	return u
}

// SetAuto sets the "auto" field.
func (u *AliasUpsert) SetAuto(v bool) *AliasUpsert {
	u.Set(alias.FieldAuto, v)
	return u
}

// UpdateAuto sets the "auto" field to the value that was provided on create.
func (u *AliasUpsert) UpdateAuto() *AliasUpsert {
	u.SetExcluded(alias.FieldAuto)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Alias.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AliasUpsertOne) UpdateNewValues() *AliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(alias.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Alias.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AliasUpsertOne) Ignore() *AliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AliasUpsertOne) DoNothing() *AliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AliasCreate.OnConflict
// documentation for more info.
func (u *AliasUpsertOne) Update(set func(*AliasUpsert)) *AliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AliasUpsert{UpdateSet: update})
	}))
	return u
}

// SetSource sets the "source" field.
func (u *AliasUpsertOne) SetSource(v string) *AliasUpsertOne {
	return u.Update(func(s *AliasUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AliasUpsertOne) UpdateSource() *AliasUpsertOne {
	return u.Update(func(s *AliasUpsert) {
		s.UpdateSource()
	})
}

// SetDestinations sets the "destinations" field.
func (u *AliasUpsertOne) SetDestinations(v []string) *AliasUpsertOne {
	return u.Update(func(s *AliasUpsert) {
		s.SetDestinations(v)
	})
}

// UpdateDestinations sets the "destinations" field to the value that was provided on create.
func (u *AliasUpsertOne) UpdateDestinations() *AliasUpsertOne {
	return u.Update(func(s *AliasUpsert) {
		s.UpdateDestinations()
	})
}

// SetPermittedSenders sets the "permitted_senders" field.
func (u *AliasUpsertOne) SetPermittedSenders(v []string) *AliasUpsertOne {
	return u.Update(func(s *AliasUpsert) {
		s.SetPermittedSenders(v)
	})
}

// UpdatePermittedSenders sets the "permitted_senders" field to the value that was provided on create.
func (u *AliasUpsertOne) UpdatePermittedSenders() *AliasUpsertOne {
	return u.Update(func(s *AliasUpsert) {
		s.UpdatePermittedSenders()
	})
}

// ClearPermittedSenders clears the value of the "permitted_senders" field.
func (u *AliasUpsertOne) ClearPermittedSenders() *AliasUpsertOne {
	return u.Update(func(s *AliasUpsert) {
		s.ClearPermittedSenders()
	})
}

// SetAuto sets the "auto" field.
func (u *AliasUpsertOne) SetAuto(v bool) *AliasUpsertOne {
	return u.Update(func(s *AliasUpsert) {
		s.SetAuto(v)
	})
}

// UpdateAuto sets the "auto" field to the value that was provided on create.
func (u *AliasUpsertOne) UpdateAuto() *AliasUpsertOne {
	return u.Update(func(s *AliasUpsert) {
		s.UpdateAuto()
	})
}

// Exec executes the query.
func (u *AliasUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AliasCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AliasUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AliasUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AliasUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AliasCreateBulk is the builder for creating many Alias entities in bulk.
type AliasCreateBulk struct {
	config
	err      error
	builders []*AliasCreate
	conflict []sql.ConflictOption
}

// Save creates the Alias entities in the database.
func (_c *AliasCreateBulk) Save(ctx context.Context) ([]*Alias, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Alias, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AliasCreateBulk) SaveX(ctx context.Context) []*Alias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AliasCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AliasCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Alias.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AliasUpsert) {
//			SetSource(v+v).
//		}).
//		Exec(ctx)
func (_c *AliasCreateBulk) OnConflict(opts ...sql.ConflictOption) *AliasUpsertBulk {
	_c.conflict = opts
	return &AliasUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Alias.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AliasCreateBulk) OnConflictColumns(columns ...string) *AliasUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AliasUpsertBulk{
		create: _c,
	}
}

// AliasUpsertBulk is the builder for "upsert"-ing
// a bulk of Alias nodes.
type AliasUpsertBulk struct {
	create *AliasCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Alias.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AliasUpsertBulk) UpdateNewValues() *AliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(alias.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Alias.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AliasUpsertBulk) Ignore() *AliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AliasUpsertBulk) DoNothing() *AliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AliasCreateBulk.OnConflict
// documentation for more info.
func (u *AliasUpsertBulk) Update(set func(*AliasUpsert)) *AliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AliasUpsert{UpdateSet: update})
	}))
	return u
}

// SetSource sets the "source" field.
func (u *AliasUpsertBulk) SetSource(v string) *AliasUpsertBulk {
	return u.Update(func(s *AliasUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AliasUpsertBulk) UpdateSource() *AliasUpsertBulk {
	return u.Update(func(s *AliasUpsert) {
		s.UpdateSource()
	})
}

// SetDestinations sets the "destinations" field.
func (u *AliasUpsertBulk) SetDestinations(v []string) *AliasUpsertBulk {
	return u.Update(func(s *AliasUpsert) {
		s.SetDestinations(v)
	})
}

// UpdateDestinations sets the "destinations" field to the value that was provided on create.
func (u *AliasUpsertBulk) UpdateDestinations() *AliasUpsertBulk {
	return u.Update(func(s *AliasUpsert) {
		s.UpdateDestinations()
	})
}

// SetPermittedSenders sets the "permitted_senders" field.
func (u *AliasUpsertBulk) SetPermittedSenders(v []string) *AliasUpsertBulk {
	return u.Update(func(s *AliasUpsert) {
		s.SetPermittedSenders(v)
	})
}

// UpdatePermittedSenders sets the "permitted_senders" field to the value that was provided on create.
func (u *AliasUpsertBulk) UpdatePermittedSenders() *AliasUpsertBulk {
	return u.Update(func(s *AliasUpsert) {
		s.UpdatePermittedSenders()
	})
}

// ClearPermittedSenders clears the value of the "permitted_senders" field.
func (u *AliasUpsertBulk) ClearPermittedSenders() *AliasUpsertBulk {
	return u.Update(func(s *AliasUpsert) {
		s.ClearPermittedSenders()
	})
}

// SetAuto sets the "auto" field.
func (u *AliasUpsertBulk) SetAuto(v bool) *AliasUpsertBulk {
	return u.Update(func(s *AliasUpsert) {
		s.SetAuto(v)
	})
}

// UpdateAuto sets the "auto" field to the value that was provided on create.
func (u *AliasUpsertBulk) UpdateAuto() *AliasUpsertBulk {
	return u.Update(func(s *AliasUpsert) {
		s.UpdateAuto()
	})
}

// Exec executes the query.
func (u *AliasUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AliasCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AliasCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AliasUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
