// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/authfailure"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthFailureCreate is the builder for creating a AuthFailure entity.
type AuthFailureCreate struct {
	config
	mutation *AuthFailureMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKind sets the "kind" field.
func (_c *AuthFailureCreate) SetKind(v string) *AuthFailureCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *AuthFailureCreate) SetEmail(v string) *AuthFailureCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetAt sets the "at" field.
func (_c *AuthFailureCreate) SetAt(v time.Time) *AuthFailureCreate {
	_c.mutation.SetAt(v)
	return _c
}

// SetNillableAt sets the "at" field if the given value is not nil.
func (_c *AuthFailureCreate) SetNillableAt(v *time.Time) *AuthFailureCreate {
	if v != nil {
		_c.SetAt(*v)
	}
	return _c
}

// Mutation returns the AuthFailureMutation object of the builder.
func (_c *AuthFailureCreate) Mutation() *AuthFailureMutation {
	return _c.mutation
}

// Save creates the AuthFailure in the database.
func (_c *AuthFailureCreate) Save(ctx context.Context) (*AuthFailure, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthFailureCreate) SaveX(ctx context.Context) *AuthFailure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthFailureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthFailureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthFailureCreate) defaults() {
	if _, ok := _c.mutation.At(); !ok {
		v := authfailure.DefaultAt()
		_c.mutation.SetAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthFailureCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "AuthFailure.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := authfailure.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AuthFailure.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "AuthFailure.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := authfailure.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AuthFailure.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.At(); !ok {
		return &ValidationError{Name: "at", err: errors.New(`ent: missing required field "AuthFailure.at"`)}
	}
	return nil
}

func (_c *AuthFailureCreate) sqlSave(ctx context.Context) (*AuthFailure, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthFailureCreate) createSpec() (*AuthFailure, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthFailure{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authfailure.Table, sqlgraph.NewFieldSpec(authfailure.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(authfailure.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(authfailure.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.At(); ok {
		_spec.SetField(authfailure.FieldAt, field.TypeTime, value)
		_node.At = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthFailure.Create().
//		SetKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthFailureUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthFailureCreate) OnConflict(opts ...sql.ConflictOption) *AuthFailureUpsertOne {
	_c.conflict = opts
	return &AuthFailureUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthFailure.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthFailureCreate) OnConflictColumns(columns ...string) *AuthFailureUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthFailureUpsertOne{
		create: _c,
	}
}

type (
	// AuthFailureUpsertOne is the builder for "upsert"-ing
	//  one AuthFailure node.
	AuthFailureUpsertOne struct {
		create *AuthFailureCreate
	}

	// AuthFailureUpsert is the "OnConflict" setter.
	AuthFailureUpsert struct {
		*sql.UpdateSet
	}
)

// SetKind sets the "kind" field.
func (u *AuthFailureUpsert) SetKind(v string) *AuthFailureUpsert {
	u.Set(authfailure.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AuthFailureUpsert) UpdateKind() *AuthFailureUpsert {
	u.SetExcluded(authfailure.FieldKind)
	return u
}

// SetEmail sets the "email" field.
func (u *AuthFailureUpsert) SetEmail(v string) *AuthFailureUpsert {
	u.Set(authfailure.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthFailureUpsert) UpdateEmail() *AuthFailureUpsert {
	u.SetExcluded(authfailure.FieldEmail)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AuthFailure.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuthFailureUpsertOne) UpdateNewValues() *AuthFailureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.At(); exists {
			s.SetIgnore(authfailure.FieldAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthFailure.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthFailureUpsertOne) Ignore() *AuthFailureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthFailureUpsertOne) DoNothing() *AuthFailureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthFailureCreate.OnConflict
// documentation for more info.
func (u *AuthFailureUpsertOne) Update(set func(*AuthFailureUpsert)) *AuthFailureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthFailureUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *AuthFailureUpsertOne) SetKind(v string) *AuthFailureUpsertOne {
	return u.Update(func(s *AuthFailureUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AuthFailureUpsertOne) UpdateKind() *AuthFailureUpsertOne {
	return u.Update(func(s *AuthFailureUpsert) {
		s.UpdateKind()
	})
}

// SetEmail sets the "email" field.
func (u *AuthFailureUpsertOne) SetEmail(v string) *AuthFailureUpsertOne {
	return u.Update(func(s *AuthFailureUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthFailureUpsertOne) UpdateEmail() *AuthFailureUpsertOne {
	return u.Update(func(s *AuthFailureUpsert) {
		s.UpdateEmail()
	})
}

// Exec executes the query.
func (u *AuthFailureUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthFailureCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthFailureUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthFailureUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthFailureUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthFailureCreateBulk is the builder for creating many AuthFailure entities in bulk.
type AuthFailureCreateBulk struct {
	config
	err      error
	builders []*AuthFailureCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthFailure entities in the database.
func (_c *AuthFailureCreateBulk) Save(ctx context.Context) ([]*AuthFailure, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthFailure, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthFailureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthFailureCreateBulk) SaveX(ctx context.Context) []*AuthFailure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthFailureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthFailureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthFailure.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthFailureUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthFailureCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthFailureUpsertBulk {
	_c.conflict = opts
	return &AuthFailureUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthFailure.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthFailureCreateBulk) OnConflictColumns(columns ...string) *AuthFailureUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthFailureUpsertBulk{
		create: _c,
	}
}

// AuthFailureUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthFailure nodes.
type AuthFailureUpsertBulk struct {
	create *AuthFailureCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthFailure.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuthFailureUpsertBulk) UpdateNewValues() *AuthFailureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.At(); exists {
				s.SetIgnore(authfailure.FieldAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthFailure.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthFailureUpsertBulk) Ignore() *AuthFailureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthFailureUpsertBulk) DoNothing() *AuthFailureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthFailureCreateBulk.OnConflict
// documentation for more info.
func (u *AuthFailureUpsertBulk) Update(set func(*AuthFailureUpsert)) *AuthFailureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthFailureUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *AuthFailureUpsertBulk) SetKind(v string) *AuthFailureUpsertBulk {
	return u.Update(func(s *AuthFailureUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AuthFailureUpsertBulk) UpdateKind() *AuthFailureUpsertBulk {
	return u.Update(func(s *AuthFailureUpsert) {
		s.UpdateKind()
	})
}

// SetEmail sets the "email" field.
func (u *AuthFailureUpsertBulk) SetEmail(v string) *AuthFailureUpsertBulk {
	return u.Update(func(s *AuthFailureUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthFailureUpsertBulk) UpdateEmail() *AuthFailureUpsertBulk {
	return u.Update(func(s *AuthFailureUpsert) {
		s.UpdateEmail()
	})
}

// Exec executes the query.
func (u *AuthFailureUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthFailureCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthFailureCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthFailureUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
