// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"naust/daemon/internal/store/ent/dnsrecord"
	"naust/daemon/internal/store/ent/tenant"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DNSRecord is the model entity for the DNSRecord schema.
type DNSRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Qname holds the value of the "qname" field.
	Qname string `json:"qname,omitempty"`
	// Rtype holds the value of the "rtype" field.
	Rtype dnsrecord.Rtype `json:"rtype,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DNSRecordQuery when eager-loading is set.
	Edges              DNSRecordEdges `json:"edges"`
	tenant_dns_records *int
	selectValues       sql.SelectValues
}

// DNSRecordEdges holds the relations/edges for other nodes in the graph.
type DNSRecordEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DNSRecordEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DNSRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dnsrecord.FieldID:
			values[i] = new(sql.NullInt64)
		case dnsrecord.FieldQname, dnsrecord.FieldRtype, dnsrecord.FieldValue:
			values[i] = new(sql.NullString)
		case dnsrecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case dnsrecord.ForeignKeys[0]: // tenant_dns_records
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DNSRecord fields.
func (_m *DNSRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dnsrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dnsrecord.FieldQname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qname", values[i])
			} else if value.Valid {
				_m.Qname = value.String
			}
		case dnsrecord.FieldRtype:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rtype", values[i])
			} else if value.Valid {
				_m.Rtype = dnsrecord.Rtype(value.String)
			}
		case dnsrecord.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case dnsrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dnsrecord.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_dns_records", value)
			} else if value.Valid {
				_m.tenant_dns_records = new(int)
				*_m.tenant_dns_records = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the DNSRecord.
// This includes values selected through modifiers, order, etc.
func (_m *DNSRecord) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the DNSRecord entity.
func (_m *DNSRecord) QueryTenant() *TenantQuery {
	return NewDNSRecordClient(_m.config).QueryTenant(_m)
}

// Update returns a builder for updating this DNSRecord.
// Note that you need to call DNSRecord.Unwrap() before calling this method if this DNSRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DNSRecord) Update() *DNSRecordUpdateOne {
	return NewDNSRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DNSRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DNSRecord) Unwrap() *DNSRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DNSRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DNSRecord) String() string {
	var builder strings.Builder
	builder.WriteString("DNSRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("qname=")
	builder.WriteString(_m.Qname)
	builder.WriteString(", ")
	builder.WriteString("rtype=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rtype))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DNSRecords is a parsable slice of DNSRecord.
type DNSRecords []*DNSRecord
