// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"naust/daemon/internal/store/ent/dnszoneprovider"
	"naust/daemon/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DNSZoneProviderDelete is the builder for deleting a DNSZoneProvider entity.
type DNSZoneProviderDelete struct {
	config
	hooks    []Hook
	mutation *DNSZoneProviderMutation
}

// Where appends a list predicates to the DNSZoneProviderDelete builder.
func (_d *DNSZoneProviderDelete) Where(ps ...predicate.DNSZoneProvider) *DNSZoneProviderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DNSZoneProviderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DNSZoneProviderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DNSZoneProviderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dnszoneprovider.Table, sqlgraph.NewFieldSpec(dnszoneprovider.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DNSZoneProviderDeleteOne is the builder for deleting a single DNSZoneProvider entity.
type DNSZoneProviderDeleteOne struct {
	_d *DNSZoneProviderDelete
}

// Where appends a list predicates to the DNSZoneProviderDelete builder.
func (_d *DNSZoneProviderDeleteOne) Where(ps ...predicate.DNSZoneProvider) *DNSZoneProviderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DNSZoneProviderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dnszoneprovider.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DNSZoneProviderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
