// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/dnszoneprovider"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/tenant"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DNSZoneProviderUpdate is the builder for updating DNSZoneProvider entities.
type DNSZoneProviderUpdate struct {
	config
	hooks    []Hook
	mutation *DNSZoneProviderMutation
}

// Where appends a list predicates to the DNSZoneProviderUpdate builder.
func (_u *DNSZoneProviderUpdate) Where(ps ...predicate.DNSZoneProvider) *DNSZoneProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetZone sets the "zone" field.
func (_u *DNSZoneProviderUpdate) SetZone(v string) *DNSZoneProviderUpdate {
	_u.mutation.SetZone(v)
	return _u
}

// SetNillableZone sets the "zone" field if the given value is not nil.
func (_u *DNSZoneProviderUpdate) SetNillableZone(v *string) *DNSZoneProviderUpdate {
	if v != nil {
		_u.SetZone(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *DNSZoneProviderUpdate) SetProvider(v string) *DNSZoneProviderUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *DNSZoneProviderUpdate) SetNillableProvider(v *string) *DNSZoneProviderUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *DNSZoneProviderUpdate) SetToken(v string) *DNSZoneProviderUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *DNSZoneProviderUpdate) SetNillableToken(v *string) *DNSZoneProviderUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *DNSZoneProviderUpdate) SetTenantID(id int) *DNSZoneProviderUpdate {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *DNSZoneProviderUpdate) SetTenant(v *Tenant) *DNSZoneProviderUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the DNSZoneProviderMutation object of the builder.
func (_u *DNSZoneProviderUpdate) Mutation() *DNSZoneProviderMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *DNSZoneProviderUpdate) ClearTenant() *DNSZoneProviderUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DNSZoneProviderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DNSZoneProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DNSZoneProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DNSZoneProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DNSZoneProviderUpdate) check() error {
	if v, ok := _u.mutation.Zone(); ok {
		if err := dnszoneprovider.ZoneValidator(v); err != nil {
			return &ValidationError{Name: "zone", err: fmt.Errorf(`ent: validator failed for field "DNSZoneProvider.zone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := dnszoneprovider.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "DNSZoneProvider.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := dnszoneprovider.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "DNSZoneProvider.token": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DNSZoneProvider.tenant"`)
	}
	return nil
}

func (_u *DNSZoneProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dnszoneprovider.Table, dnszoneprovider.Columns, sqlgraph.NewFieldSpec(dnszoneprovider.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Zone(); ok {
		_spec.SetField(dnszoneprovider.FieldZone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(dnszoneprovider.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(dnszoneprovider.FieldToken, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnszoneprovider.TenantTable,
			Columns: []string{dnszoneprovider.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnszoneprovider.TenantTable,
			Columns: []string{dnszoneprovider.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnszoneprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DNSZoneProviderUpdateOne is the builder for updating a single DNSZoneProvider entity.
type DNSZoneProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DNSZoneProviderMutation
}

// SetZone sets the "zone" field.
func (_u *DNSZoneProviderUpdateOne) SetZone(v string) *DNSZoneProviderUpdateOne {
	_u.mutation.SetZone(v)
	return _u
}

// SetNillableZone sets the "zone" field if the given value is not nil.
func (_u *DNSZoneProviderUpdateOne) SetNillableZone(v *string) *DNSZoneProviderUpdateOne {
	if v != nil {
		_u.SetZone(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *DNSZoneProviderUpdateOne) SetProvider(v string) *DNSZoneProviderUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *DNSZoneProviderUpdateOne) SetNillableProvider(v *string) *DNSZoneProviderUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *DNSZoneProviderUpdateOne) SetToken(v string) *DNSZoneProviderUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *DNSZoneProviderUpdateOne) SetNillableToken(v *string) *DNSZoneProviderUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *DNSZoneProviderUpdateOne) SetTenantID(id int) *DNSZoneProviderUpdateOne {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *DNSZoneProviderUpdateOne) SetTenant(v *Tenant) *DNSZoneProviderUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the DNSZoneProviderMutation object of the builder.
func (_u *DNSZoneProviderUpdateOne) Mutation() *DNSZoneProviderMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *DNSZoneProviderUpdateOne) ClearTenant() *DNSZoneProviderUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the DNSZoneProviderUpdate builder.
func (_u *DNSZoneProviderUpdateOne) Where(ps ...predicate.DNSZoneProvider) *DNSZoneProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DNSZoneProviderUpdateOne) Select(field string, fields ...string) *DNSZoneProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DNSZoneProvider entity.
func (_u *DNSZoneProviderUpdateOne) Save(ctx context.Context) (*DNSZoneProvider, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DNSZoneProviderUpdateOne) SaveX(ctx context.Context) *DNSZoneProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DNSZoneProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DNSZoneProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DNSZoneProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Zone(); ok {
		if err := dnszoneprovider.ZoneValidator(v); err != nil {
			return &ValidationError{Name: "zone", err: fmt.Errorf(`ent: validator failed for field "DNSZoneProvider.zone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := dnszoneprovider.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "DNSZoneProvider.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := dnszoneprovider.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "DNSZoneProvider.token": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DNSZoneProvider.tenant"`)
	}
	return nil
}

func (_u *DNSZoneProviderUpdateOne) sqlSave(ctx context.Context) (_node *DNSZoneProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dnszoneprovider.Table, dnszoneprovider.Columns, sqlgraph.NewFieldSpec(dnszoneprovider.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DNSZoneProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dnszoneprovider.FieldID)
		for _, f := range fields {
			if !dnszoneprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dnszoneprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Zone(); ok {
		_spec.SetField(dnszoneprovider.FieldZone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(dnszoneprovider.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(dnszoneprovider.FieldToken, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnszoneprovider.TenantTable,
			Columns: []string{dnszoneprovider.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnszoneprovider.TenantTable,
			Columns: []string{dnszoneprovider.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DNSZoneProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnszoneprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
