// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"naust/daemon/internal/store/ent/dnszoneprovider"
	"naust/daemon/internal/store/ent/tenant"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DNSZoneProvider is the model entity for the DNSZoneProvider schema.
type DNSZoneProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Zone holds the value of the "zone" field.
	Zone string `json:"zone,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DNSZoneProviderQuery when eager-loading is set.
	Edges                     DNSZoneProviderEdges `json:"edges"`
	tenant_dns_zone_providers *int
	selectValues              sql.SelectValues
}

// DNSZoneProviderEdges holds the relations/edges for other nodes in the graph.
type DNSZoneProviderEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DNSZoneProviderEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DNSZoneProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dnszoneprovider.FieldID:
			values[i] = new(sql.NullInt64)
		case dnszoneprovider.FieldZone, dnszoneprovider.FieldProvider, dnszoneprovider.FieldToken:
			values[i] = new(sql.NullString)
		case dnszoneprovider.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case dnszoneprovider.ForeignKeys[0]: // tenant_dns_zone_providers
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DNSZoneProvider fields.
func (_m *DNSZoneProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dnszoneprovider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dnszoneprovider.FieldZone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field zone", values[i])
			} else if value.Valid {
				_m.Zone = value.String
			}
		case dnszoneprovider.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case dnszoneprovider.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case dnszoneprovider.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dnszoneprovider.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_dns_zone_providers", value)
			} else if value.Valid {
				_m.tenant_dns_zone_providers = new(int)
				*_m.tenant_dns_zone_providers = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DNSZoneProvider.
// This includes values selected through modifiers, order, etc.
func (_m *DNSZoneProvider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the DNSZoneProvider entity.
func (_m *DNSZoneProvider) QueryTenant() *TenantQuery {
	return NewDNSZoneProviderClient(_m.config).QueryTenant(_m)
}

// Update returns a builder for updating this DNSZoneProvider.
// Note that you need to call DNSZoneProvider.Unwrap() before calling this method if this DNSZoneProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DNSZoneProvider) Update() *DNSZoneProviderUpdateOne {
	return NewDNSZoneProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DNSZoneProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DNSZoneProvider) Unwrap() *DNSZoneProvider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DNSZoneProvider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DNSZoneProvider) String() string {
	var builder strings.Builder
	builder.WriteString("DNSZoneProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("zone=")
	builder.WriteString(_m.Zone)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DNSZoneProviders is a parsable slice of DNSZoneProvider.
type DNSZoneProviders []*DNSZoneProvider
