// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/encryptionsetup"
	"naust/daemon/internal/store/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EncryptionSetupCreate is the builder for creating a EncryptionSetup entity.
type EncryptionSetupCreate struct {
	config
	mutation *EncryptionSetupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMode sets the "mode" field.
func (_c *EncryptionSetupCreate) SetMode(v encryptionsetup.Mode) *EncryptionSetupCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetPrepared sets the "prepared" field.
func (_c *EncryptionSetupCreate) SetPrepared(v string) *EncryptionSetupCreate {
	_c.mutation.SetPrepared(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *EncryptionSetupCreate) SetAttempts(v int) *EncryptionSetupCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *EncryptionSetupCreate) SetNillableAttempts(v *int) *EncryptionSetupCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EncryptionSetupCreate) SetExpiresAt(v time.Time) *EncryptionSetupCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *EncryptionSetupCreate) SetUserID(id int) *EncryptionSetupCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *EncryptionSetupCreate) SetUser(v *User) *EncryptionSetupCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the EncryptionSetupMutation object of the builder.
func (_c *EncryptionSetupCreate) Mutation() *EncryptionSetupMutation {
	return _c.mutation
}

// Save creates the EncryptionSetup in the database.
func (_c *EncryptionSetupCreate) Save(ctx context.Context) (*EncryptionSetup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EncryptionSetupCreate) SaveX(ctx context.Context) *EncryptionSetup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EncryptionSetupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EncryptionSetupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EncryptionSetupCreate) defaults() {
	if _, ok := _c.mutation.Attempts(); !ok {
		v := encryptionsetup.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EncryptionSetupCreate) check() error {
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "EncryptionSetup.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := encryptionsetup.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "EncryptionSetup.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prepared(); !ok {
		return &ValidationError{Name: "prepared", err: errors.New(`ent: missing required field "EncryptionSetup.prepared"`)}
	}
	if v, ok := _c.mutation.Prepared(); ok {
		if err := encryptionsetup.PreparedValidator(v); err != nil {
			return &ValidationError{Name: "prepared", err: fmt.Errorf(`ent: validator failed for field "EncryptionSetup.prepared": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "EncryptionSetup.attempts"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "EncryptionSetup.expires_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "EncryptionSetup.user"`)}
	}
	return nil
}

func (_c *EncryptionSetupCreate) sqlSave(ctx context.Context) (*EncryptionSetup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EncryptionSetupCreate) createSpec() (*EncryptionSetup, *sqlgraph.CreateSpec) {
	var (
		_node = &EncryptionSetup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(encryptionsetup.Table, sqlgraph.NewFieldSpec(encryptionsetup.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(encryptionsetup.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Prepared(); ok {
		_spec.SetField(encryptionsetup.FieldPrepared, field.TypeString, value)
		_node.Prepared = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(encryptionsetup.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(encryptionsetup.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   encryptionsetup.UserTable,
			Columns: []string{encryptionsetup.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_encryption_setups = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EncryptionSetup.Create().
//		SetMode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EncryptionSetupUpsert) {
//			SetMode(v+v).
//		}).
//		Exec(ctx)
func (_c *EncryptionSetupCreate) OnConflict(opts ...sql.ConflictOption) *EncryptionSetupUpsertOne {
	_c.conflict = opts
	return &EncryptionSetupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EncryptionSetup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EncryptionSetupCreate) OnConflictColumns(columns ...string) *EncryptionSetupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EncryptionSetupUpsertOne{
		create: _c,
	}
}

type (
	// EncryptionSetupUpsertOne is the builder for "upsert"-ing
	//  one EncryptionSetup node.
	EncryptionSetupUpsertOne struct {
		create *EncryptionSetupCreate
	}

	// EncryptionSetupUpsert is the "OnConflict" setter.
	EncryptionSetupUpsert struct {
		*sql.UpdateSet
	}
)

// SetMode sets the "mode" field.
func (u *EncryptionSetupUpsert) SetMode(v encryptionsetup.Mode) *EncryptionSetupUpsert {
	u.Set(encryptionsetup.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *EncryptionSetupUpsert) UpdateMode() *EncryptionSetupUpsert {
	u.SetExcluded(encryptionsetup.FieldMode)
	return u
}

// SetPrepared sets the "prepared" field.
func (u *EncryptionSetupUpsert) SetPrepared(v string) *EncryptionSetupUpsert {
	u.Set(encryptionsetup.FieldPrepared, v)
	return u
}

// UpdatePrepared sets the "prepared" field to the value that was provided on create.
func (u *EncryptionSetupUpsert) UpdatePrepared() *EncryptionSetupUpsert {
	u.SetExcluded(encryptionsetup.FieldPrepared)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *EncryptionSetupUpsert) SetAttempts(v int) *EncryptionSetupUpsert {
	u.Set(encryptionsetup.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EncryptionSetupUpsert) UpdateAttempts() *EncryptionSetupUpsert {
	u.SetExcluded(encryptionsetup.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *EncryptionSetupUpsert) AddAttempts(v int) *EncryptionSetupUpsert {
	u.Add(encryptionsetup.FieldAttempts, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *EncryptionSetupUpsert) SetExpiresAt(v time.Time) *EncryptionSetupUpsert {
	u.Set(encryptionsetup.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EncryptionSetupUpsert) UpdateExpiresAt() *EncryptionSetupUpsert {
	u.SetExcluded(encryptionsetup.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EncryptionSetup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EncryptionSetupUpsertOne) UpdateNewValues() *EncryptionSetupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EncryptionSetup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EncryptionSetupUpsertOne) Ignore() *EncryptionSetupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EncryptionSetupUpsertOne) DoNothing() *EncryptionSetupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EncryptionSetupCreate.OnConflict
// documentation for more info.
func (u *EncryptionSetupUpsertOne) Update(set func(*EncryptionSetupUpsert)) *EncryptionSetupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EncryptionSetupUpsert{UpdateSet: update})
	}))
	return u
}

// SetMode sets the "mode" field.
func (u *EncryptionSetupUpsertOne) SetMode(v encryptionsetup.Mode) *EncryptionSetupUpsertOne {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *EncryptionSetupUpsertOne) UpdateMode() *EncryptionSetupUpsertOne {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.UpdateMode()
	})
}

// SetPrepared sets the "prepared" field.
func (u *EncryptionSetupUpsertOne) SetPrepared(v string) *EncryptionSetupUpsertOne {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.SetPrepared(v)
	})
}

// UpdatePrepared sets the "prepared" field to the value that was provided on create.
func (u *EncryptionSetupUpsertOne) UpdatePrepared() *EncryptionSetupUpsertOne {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.UpdatePrepared()
	})
}

// SetAttempts sets the "attempts" field.
func (u *EncryptionSetupUpsertOne) SetAttempts(v int) *EncryptionSetupUpsertOne {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *EncryptionSetupUpsertOne) AddAttempts(v int) *EncryptionSetupUpsertOne {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EncryptionSetupUpsertOne) UpdateAttempts() *EncryptionSetupUpsertOne {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.UpdateAttempts()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EncryptionSetupUpsertOne) SetExpiresAt(v time.Time) *EncryptionSetupUpsertOne {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EncryptionSetupUpsertOne) UpdateExpiresAt() *EncryptionSetupUpsertOne {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *EncryptionSetupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EncryptionSetupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EncryptionSetupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EncryptionSetupUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EncryptionSetupUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EncryptionSetupCreateBulk is the builder for creating many EncryptionSetup entities in bulk.
type EncryptionSetupCreateBulk struct {
	config
	err      error
	builders []*EncryptionSetupCreate
	conflict []sql.ConflictOption
}

// Save creates the EncryptionSetup entities in the database.
func (_c *EncryptionSetupCreateBulk) Save(ctx context.Context) ([]*EncryptionSetup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EncryptionSetup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EncryptionSetupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EncryptionSetupCreateBulk) SaveX(ctx context.Context) []*EncryptionSetup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EncryptionSetupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EncryptionSetupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EncryptionSetup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EncryptionSetupUpsert) {
//			SetMode(v+v).
//		}).
//		Exec(ctx)
func (_c *EncryptionSetupCreateBulk) OnConflict(opts ...sql.ConflictOption) *EncryptionSetupUpsertBulk {
	_c.conflict = opts
	return &EncryptionSetupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EncryptionSetup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EncryptionSetupCreateBulk) OnConflictColumns(columns ...string) *EncryptionSetupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EncryptionSetupUpsertBulk{
		create: _c,
	}
}

// EncryptionSetupUpsertBulk is the builder for "upsert"-ing
// a bulk of EncryptionSetup nodes.
type EncryptionSetupUpsertBulk struct {
	create *EncryptionSetupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EncryptionSetup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EncryptionSetupUpsertBulk) UpdateNewValues() *EncryptionSetupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EncryptionSetup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EncryptionSetupUpsertBulk) Ignore() *EncryptionSetupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EncryptionSetupUpsertBulk) DoNothing() *EncryptionSetupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EncryptionSetupCreateBulk.OnConflict
// documentation for more info.
func (u *EncryptionSetupUpsertBulk) Update(set func(*EncryptionSetupUpsert)) *EncryptionSetupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EncryptionSetupUpsert{UpdateSet: update})
	}))
	return u
}

// SetMode sets the "mode" field.
func (u *EncryptionSetupUpsertBulk) SetMode(v encryptionsetup.Mode) *EncryptionSetupUpsertBulk {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *EncryptionSetupUpsertBulk) UpdateMode() *EncryptionSetupUpsertBulk {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.UpdateMode()
	})
}

// SetPrepared sets the "prepared" field.
func (u *EncryptionSetupUpsertBulk) SetPrepared(v string) *EncryptionSetupUpsertBulk {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.SetPrepared(v)
	})
}

// UpdatePrepared sets the "prepared" field to the value that was provided on create.
func (u *EncryptionSetupUpsertBulk) UpdatePrepared() *EncryptionSetupUpsertBulk {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.UpdatePrepared()
	})
}

// SetAttempts sets the "attempts" field.
func (u *EncryptionSetupUpsertBulk) SetAttempts(v int) *EncryptionSetupUpsertBulk {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *EncryptionSetupUpsertBulk) AddAttempts(v int) *EncryptionSetupUpsertBulk {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EncryptionSetupUpsertBulk) UpdateAttempts() *EncryptionSetupUpsertBulk {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.UpdateAttempts()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EncryptionSetupUpsertBulk) SetExpiresAt(v time.Time) *EncryptionSetupUpsertBulk {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EncryptionSetupUpsertBulk) UpdateExpiresAt() *EncryptionSetupUpsertBulk {
	return u.Update(func(s *EncryptionSetupUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *EncryptionSetupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EncryptionSetupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EncryptionSetupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EncryptionSetupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
