// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/encryptionsetup"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EncryptionSetupUpdate is the builder for updating EncryptionSetup entities.
type EncryptionSetupUpdate struct {
	config
	hooks    []Hook
	mutation *EncryptionSetupMutation
}

// Where appends a list predicates to the EncryptionSetupUpdate builder.
func (_u *EncryptionSetupUpdate) Where(ps ...predicate.EncryptionSetup) *EncryptionSetupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMode sets the "mode" field.
func (_u *EncryptionSetupUpdate) SetMode(v encryptionsetup.Mode) *EncryptionSetupUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *EncryptionSetupUpdate) SetNillableMode(v *encryptionsetup.Mode) *EncryptionSetupUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetPrepared sets the "prepared" field.
func (_u *EncryptionSetupUpdate) SetPrepared(v string) *EncryptionSetupUpdate {
	_u.mutation.SetPrepared(v)
	return _u
}

// SetNillablePrepared sets the "prepared" field if the given value is not nil.
func (_u *EncryptionSetupUpdate) SetNillablePrepared(v *string) *EncryptionSetupUpdate {
	if v != nil {
		_u.SetPrepared(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EncryptionSetupUpdate) SetAttempts(v int) *EncryptionSetupUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EncryptionSetupUpdate) SetNillableAttempts(v *int) *EncryptionSetupUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EncryptionSetupUpdate) AddAttempts(v int) *EncryptionSetupUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EncryptionSetupUpdate) SetExpiresAt(v time.Time) *EncryptionSetupUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EncryptionSetupUpdate) SetNillableExpiresAt(v *time.Time) *EncryptionSetupUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *EncryptionSetupUpdate) SetUserID(id int) *EncryptionSetupUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EncryptionSetupUpdate) SetUser(v *User) *EncryptionSetupUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the EncryptionSetupMutation object of the builder.
func (_u *EncryptionSetupUpdate) Mutation() *EncryptionSetupMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EncryptionSetupUpdate) ClearUser() *EncryptionSetupUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EncryptionSetupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EncryptionSetupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EncryptionSetupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EncryptionSetupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EncryptionSetupUpdate) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := encryptionsetup.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "EncryptionSetup.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prepared(); ok {
		if err := encryptionsetup.PreparedValidator(v); err != nil {
			return &ValidationError{Name: "prepared", err: fmt.Errorf(`ent: validator failed for field "EncryptionSetup.prepared": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EncryptionSetup.user"`)
	}
	return nil
}

func (_u *EncryptionSetupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(encryptionsetup.Table, encryptionsetup.Columns, sqlgraph.NewFieldSpec(encryptionsetup.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(encryptionsetup.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Prepared(); ok {
		_spec.SetField(encryptionsetup.FieldPrepared, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(encryptionsetup.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(encryptionsetup.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(encryptionsetup.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   encryptionsetup.UserTable,
			Columns: []string{encryptionsetup.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   encryptionsetup.UserTable,
			Columns: []string{encryptionsetup.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{encryptionsetup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EncryptionSetupUpdateOne is the builder for updating a single EncryptionSetup entity.
type EncryptionSetupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EncryptionSetupMutation
}

// SetMode sets the "mode" field.
func (_u *EncryptionSetupUpdateOne) SetMode(v encryptionsetup.Mode) *EncryptionSetupUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *EncryptionSetupUpdateOne) SetNillableMode(v *encryptionsetup.Mode) *EncryptionSetupUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetPrepared sets the "prepared" field.
func (_u *EncryptionSetupUpdateOne) SetPrepared(v string) *EncryptionSetupUpdateOne {
	_u.mutation.SetPrepared(v)
	return _u
}

// SetNillablePrepared sets the "prepared" field if the given value is not nil.
func (_u *EncryptionSetupUpdateOne) SetNillablePrepared(v *string) *EncryptionSetupUpdateOne {
	if v != nil {
		_u.SetPrepared(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EncryptionSetupUpdateOne) SetAttempts(v int) *EncryptionSetupUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EncryptionSetupUpdateOne) SetNillableAttempts(v *int) *EncryptionSetupUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EncryptionSetupUpdateOne) AddAttempts(v int) *EncryptionSetupUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EncryptionSetupUpdateOne) SetExpiresAt(v time.Time) *EncryptionSetupUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EncryptionSetupUpdateOne) SetNillableExpiresAt(v *time.Time) *EncryptionSetupUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *EncryptionSetupUpdateOne) SetUserID(id int) *EncryptionSetupUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EncryptionSetupUpdateOne) SetUser(v *User) *EncryptionSetupUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the EncryptionSetupMutation object of the builder.
func (_u *EncryptionSetupUpdateOne) Mutation() *EncryptionSetupMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EncryptionSetupUpdateOne) ClearUser() *EncryptionSetupUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the EncryptionSetupUpdate builder.
func (_u *EncryptionSetupUpdateOne) Where(ps ...predicate.EncryptionSetup) *EncryptionSetupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EncryptionSetupUpdateOne) Select(field string, fields ...string) *EncryptionSetupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EncryptionSetup entity.
func (_u *EncryptionSetupUpdateOne) Save(ctx context.Context) (*EncryptionSetup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EncryptionSetupUpdateOne) SaveX(ctx context.Context) *EncryptionSetup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EncryptionSetupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EncryptionSetupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EncryptionSetupUpdateOne) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := encryptionsetup.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "EncryptionSetup.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prepared(); ok {
		if err := encryptionsetup.PreparedValidator(v); err != nil {
			return &ValidationError{Name: "prepared", err: fmt.Errorf(`ent: validator failed for field "EncryptionSetup.prepared": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EncryptionSetup.user"`)
	}
	return nil
}

func (_u *EncryptionSetupUpdateOne) sqlSave(ctx context.Context) (_node *EncryptionSetup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(encryptionsetup.Table, encryptionsetup.Columns, sqlgraph.NewFieldSpec(encryptionsetup.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EncryptionSetup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, encryptionsetup.FieldID)
		for _, f := range fields {
			if !encryptionsetup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != encryptionsetup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(encryptionsetup.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Prepared(); ok {
		_spec.SetField(encryptionsetup.FieldPrepared, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(encryptionsetup.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(encryptionsetup.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(encryptionsetup.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   encryptionsetup.UserTable,
			Columns: []string{encryptionsetup.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   encryptionsetup.UserTable,
			Columns: []string{encryptionsetup.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EncryptionSetup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{encryptionsetup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
