// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"naust/daemon/internal/store/ent/mailkeyslot"
	"naust/daemon/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MailKeySlotDelete is the builder for deleting a MailKeySlot entity.
type MailKeySlotDelete struct {
	config
	hooks    []Hook
	mutation *MailKeySlotMutation
}

// Where appends a list predicates to the MailKeySlotDelete builder.
func (_d *MailKeySlotDelete) Where(ps ...predicate.MailKeySlot) *MailKeySlotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MailKeySlotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MailKeySlotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MailKeySlotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mailkeyslot.Table, sqlgraph.NewFieldSpec(mailkeyslot.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MailKeySlotDeleteOne is the builder for deleting a single MailKeySlot entity.
type MailKeySlotDeleteOne struct {
	_d *MailKeySlotDelete
}

// Where appends a list predicates to the MailKeySlotDelete builder.
func (_d *MailKeySlotDeleteOne) Where(ps ...predicate.MailKeySlot) *MailKeySlotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MailKeySlotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mailkeyslot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MailKeySlotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
