// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/mailkeyslot"
	"naust/daemon/internal/store/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MailKeySlotCreate is the builder for creating a MailKeySlot entity.
type MailKeySlotCreate struct {
	config
	mutation *MailKeySlotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSlotType sets the "slot_type" field.
func (_c *MailKeySlotCreate) SetSlotType(v mailkeyslot.SlotType) *MailKeySlotCreate {
	_c.mutation.SetSlotType(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *MailKeySlotCreate) SetLabel(v string) *MailKeySlotCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *MailKeySlotCreate) SetNillableLabel(v *string) *MailKeySlotCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *MailKeySlotCreate) SetVersion(v int) *MailKeySlotCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetWrappedKey sets the "wrapped_key" field.
func (_c *MailKeySlotCreate) SetWrappedKey(v []byte) *MailKeySlotCreate {
	_c.mutation.SetWrappedKey(v)
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *MailKeySlotCreate) SetNonce(v []byte) *MailKeySlotCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetKdfSalt sets the "kdf_salt" field.
func (_c *MailKeySlotCreate) SetKdfSalt(v []byte) *MailKeySlotCreate {
	_c.mutation.SetKdfSalt(v)
	return _c
}

// SetPrfSalt sets the "prf_salt" field.
func (_c *MailKeySlotCreate) SetPrfSalt(v []byte) *MailKeySlotCreate {
	_c.mutation.SetPrfSalt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MailKeySlotCreate) SetCreatedAt(v time.Time) *MailKeySlotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MailKeySlotCreate) SetNillableCreatedAt(v *time.Time) *MailKeySlotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *MailKeySlotCreate) SetUserID(id int) *MailKeySlotCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *MailKeySlotCreate) SetUser(v *User) *MailKeySlotCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the MailKeySlotMutation object of the builder.
func (_c *MailKeySlotCreate) Mutation() *MailKeySlotMutation {
	return _c.mutation
}

// Save creates the MailKeySlot in the database.
func (_c *MailKeySlotCreate) Save(ctx context.Context) (*MailKeySlot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MailKeySlotCreate) SaveX(ctx context.Context) *MailKeySlot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailKeySlotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailKeySlotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MailKeySlotCreate) defaults() {
	if _, ok := _c.mutation.Label(); !ok {
		v := mailkeyslot.DefaultLabel
		_c.mutation.SetLabel(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mailkeyslot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MailKeySlotCreate) check() error {
	if _, ok := _c.mutation.SlotType(); !ok {
		return &ValidationError{Name: "slot_type", err: errors.New(`ent: missing required field "MailKeySlot.slot_type"`)}
	}
	if v, ok := _c.mutation.SlotType(); ok {
		if err := mailkeyslot.SlotTypeValidator(v); err != nil {
			return &ValidationError{Name: "slot_type", err: fmt.Errorf(`ent: validator failed for field "MailKeySlot.slot_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "MailKeySlot.label"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "MailKeySlot.version"`)}
	}
	if _, ok := _c.mutation.WrappedKey(); !ok {
		return &ValidationError{Name: "wrapped_key", err: errors.New(`ent: missing required field "MailKeySlot.wrapped_key"`)}
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "MailKeySlot.nonce"`)}
	}
	if _, ok := _c.mutation.KdfSalt(); !ok {
		return &ValidationError{Name: "kdf_salt", err: errors.New(`ent: missing required field "MailKeySlot.kdf_salt"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MailKeySlot.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "MailKeySlot.user"`)}
	}
	return nil
}

func (_c *MailKeySlotCreate) sqlSave(ctx context.Context) (*MailKeySlot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MailKeySlotCreate) createSpec() (*MailKeySlot, *sqlgraph.CreateSpec) {
	var (
		_node = &MailKeySlot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mailkeyslot.Table, sqlgraph.NewFieldSpec(mailkeyslot.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SlotType(); ok {
		_spec.SetField(mailkeyslot.FieldSlotType, field.TypeEnum, value)
		_node.SlotType = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(mailkeyslot.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(mailkeyslot.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.WrappedKey(); ok {
		_spec.SetField(mailkeyslot.FieldWrappedKey, field.TypeBytes, value)
		_node.WrappedKey = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(mailkeyslot.FieldNonce, field.TypeBytes, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.KdfSalt(); ok {
		_spec.SetField(mailkeyslot.FieldKdfSalt, field.TypeBytes, value)
		_node.KdfSalt = value
	}
	if value, ok := _c.mutation.PrfSalt(); ok {
		_spec.SetField(mailkeyslot.FieldPrfSalt, field.TypeBytes, value)
		_node.PrfSalt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mailkeyslot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mailkeyslot.UserTable,
			Columns: []string{mailkeyslot.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_mail_key_slots = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MailKeySlot.Create().
//		SetSlotType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MailKeySlotUpsert) {
//			SetSlotType(v+v).
//		}).
//		Exec(ctx)
func (_c *MailKeySlotCreate) OnConflict(opts ...sql.ConflictOption) *MailKeySlotUpsertOne {
	_c.conflict = opts
	return &MailKeySlotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MailKeySlot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MailKeySlotCreate) OnConflictColumns(columns ...string) *MailKeySlotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MailKeySlotUpsertOne{
		create: _c,
	}
}

type (
	// MailKeySlotUpsertOne is the builder for "upsert"-ing
	//  one MailKeySlot node.
	MailKeySlotUpsertOne struct {
		create *MailKeySlotCreate
	}

	// MailKeySlotUpsert is the "OnConflict" setter.
	MailKeySlotUpsert struct {
		*sql.UpdateSet
	}
)

// SetSlotType sets the "slot_type" field.
func (u *MailKeySlotUpsert) SetSlotType(v mailkeyslot.SlotType) *MailKeySlotUpsert {
	u.Set(mailkeyslot.FieldSlotType, v)
	return u
}

// UpdateSlotType sets the "slot_type" field to the value that was provided on create.
func (u *MailKeySlotUpsert) UpdateSlotType() *MailKeySlotUpsert {
	u.SetExcluded(mailkeyslot.FieldSlotType)
	return u
}

// SetLabel sets the "label" field.
func (u *MailKeySlotUpsert) SetLabel(v string) *MailKeySlotUpsert {
	u.Set(mailkeyslot.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *MailKeySlotUpsert) UpdateLabel() *MailKeySlotUpsert {
	u.SetExcluded(mailkeyslot.FieldLabel)
	return u
}

// SetVersion sets the "version" field.
func (u *MailKeySlotUpsert) SetVersion(v int) *MailKeySlotUpsert {
	u.Set(mailkeyslot.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *MailKeySlotUpsert) UpdateVersion() *MailKeySlotUpsert {
	u.SetExcluded(mailkeyslot.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *MailKeySlotUpsert) AddVersion(v int) *MailKeySlotUpsert {
	u.Add(mailkeyslot.FieldVersion, v)
	return u
}

// SetWrappedKey sets the "wrapped_key" field.
func (u *MailKeySlotUpsert) SetWrappedKey(v []byte) *MailKeySlotUpsert {
	u.Set(mailkeyslot.FieldWrappedKey, v)
	return u
}

// UpdateWrappedKey sets the "wrapped_key" field to the value that was provided on create.
func (u *MailKeySlotUpsert) UpdateWrappedKey() *MailKeySlotUpsert {
	u.SetExcluded(mailkeyslot.FieldWrappedKey)
	return u
}

// SetNonce sets the "nonce" field.
func (u *MailKeySlotUpsert) SetNonce(v []byte) *MailKeySlotUpsert {
	u.Set(mailkeyslot.FieldNonce, v)
	return u
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *MailKeySlotUpsert) UpdateNonce() *MailKeySlotUpsert {
	u.SetExcluded(mailkeyslot.FieldNonce)
	return u
}

// SetKdfSalt sets the "kdf_salt" field.
func (u *MailKeySlotUpsert) SetKdfSalt(v []byte) *MailKeySlotUpsert {
	u.Set(mailkeyslot.FieldKdfSalt, v)
	return u
}

// UpdateKdfSalt sets the "kdf_salt" field to the value that was provided on create.
func (u *MailKeySlotUpsert) UpdateKdfSalt() *MailKeySlotUpsert {
	u.SetExcluded(mailkeyslot.FieldKdfSalt)
	return u
}

// SetPrfSalt sets the "prf_salt" field.
func (u *MailKeySlotUpsert) SetPrfSalt(v []byte) *MailKeySlotUpsert {
	u.Set(mailkeyslot.FieldPrfSalt, v)
	return u
}

// UpdatePrfSalt sets the "prf_salt" field to the value that was provided on create.
func (u *MailKeySlotUpsert) UpdatePrfSalt() *MailKeySlotUpsert {
	u.SetExcluded(mailkeyslot.FieldPrfSalt)
	return u
}

// ClearPrfSalt clears the value of the "prf_salt" field.
func (u *MailKeySlotUpsert) ClearPrfSalt() *MailKeySlotUpsert {
	u.SetNull(mailkeyslot.FieldPrfSalt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MailKeySlot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MailKeySlotUpsertOne) UpdateNewValues() *MailKeySlotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(mailkeyslot.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MailKeySlot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MailKeySlotUpsertOne) Ignore() *MailKeySlotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MailKeySlotUpsertOne) DoNothing() *MailKeySlotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MailKeySlotCreate.OnConflict
// documentation for more info.
func (u *MailKeySlotUpsertOne) Update(set func(*MailKeySlotUpsert)) *MailKeySlotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MailKeySlotUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlotType sets the "slot_type" field.
func (u *MailKeySlotUpsertOne) SetSlotType(v mailkeyslot.SlotType) *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetSlotType(v)
	})
}

// UpdateSlotType sets the "slot_type" field to the value that was provided on create.
func (u *MailKeySlotUpsertOne) UpdateSlotType() *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateSlotType()
	})
}

// SetLabel sets the "label" field.
func (u *MailKeySlotUpsertOne) SetLabel(v string) *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *MailKeySlotUpsertOne) UpdateLabel() *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateLabel()
	})
}

// SetVersion sets the "version" field.
func (u *MailKeySlotUpsertOne) SetVersion(v int) *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *MailKeySlotUpsertOne) AddVersion(v int) *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *MailKeySlotUpsertOne) UpdateVersion() *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateVersion()
	})
}

// SetWrappedKey sets the "wrapped_key" field.
func (u *MailKeySlotUpsertOne) SetWrappedKey(v []byte) *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetWrappedKey(v)
	})
}

// UpdateWrappedKey sets the "wrapped_key" field to the value that was provided on create.
func (u *MailKeySlotUpsertOne) UpdateWrappedKey() *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateWrappedKey()
	})
}

// SetNonce sets the "nonce" field.
func (u *MailKeySlotUpsertOne) SetNonce(v []byte) *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *MailKeySlotUpsertOne) UpdateNonce() *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateNonce()
	})
}

// SetKdfSalt sets the "kdf_salt" field.
func (u *MailKeySlotUpsertOne) SetKdfSalt(v []byte) *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetKdfSalt(v)
	})
}

// UpdateKdfSalt sets the "kdf_salt" field to the value that was provided on create.
func (u *MailKeySlotUpsertOne) UpdateKdfSalt() *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateKdfSalt()
	})
}

// SetPrfSalt sets the "prf_salt" field.
func (u *MailKeySlotUpsertOne) SetPrfSalt(v []byte) *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetPrfSalt(v)
	})
}

// UpdatePrfSalt sets the "prf_salt" field to the value that was provided on create.
func (u *MailKeySlotUpsertOne) UpdatePrfSalt() *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdatePrfSalt()
	})
}

// ClearPrfSalt clears the value of the "prf_salt" field.
func (u *MailKeySlotUpsertOne) ClearPrfSalt() *MailKeySlotUpsertOne {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.ClearPrfSalt()
	})
}

// Exec executes the query.
func (u *MailKeySlotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MailKeySlotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MailKeySlotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MailKeySlotUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MailKeySlotUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MailKeySlotCreateBulk is the builder for creating many MailKeySlot entities in bulk.
type MailKeySlotCreateBulk struct {
	config
	err      error
	builders []*MailKeySlotCreate
	conflict []sql.ConflictOption
}

// Save creates the MailKeySlot entities in the database.
func (_c *MailKeySlotCreateBulk) Save(ctx context.Context) ([]*MailKeySlot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MailKeySlot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailKeySlotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MailKeySlotCreateBulk) SaveX(ctx context.Context) []*MailKeySlot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailKeySlotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailKeySlotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MailKeySlot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MailKeySlotUpsert) {
//			SetSlotType(v+v).
//		}).
//		Exec(ctx)
func (_c *MailKeySlotCreateBulk) OnConflict(opts ...sql.ConflictOption) *MailKeySlotUpsertBulk {
	_c.conflict = opts
	return &MailKeySlotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MailKeySlot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MailKeySlotCreateBulk) OnConflictColumns(columns ...string) *MailKeySlotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MailKeySlotUpsertBulk{
		create: _c,
	}
}

// MailKeySlotUpsertBulk is the builder for "upsert"-ing
// a bulk of MailKeySlot nodes.
type MailKeySlotUpsertBulk struct {
	create *MailKeySlotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MailKeySlot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MailKeySlotUpsertBulk) UpdateNewValues() *MailKeySlotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(mailkeyslot.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MailKeySlot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MailKeySlotUpsertBulk) Ignore() *MailKeySlotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MailKeySlotUpsertBulk) DoNothing() *MailKeySlotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MailKeySlotCreateBulk.OnConflict
// documentation for more info.
func (u *MailKeySlotUpsertBulk) Update(set func(*MailKeySlotUpsert)) *MailKeySlotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MailKeySlotUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlotType sets the "slot_type" field.
func (u *MailKeySlotUpsertBulk) SetSlotType(v mailkeyslot.SlotType) *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetSlotType(v)
	})
}

// UpdateSlotType sets the "slot_type" field to the value that was provided on create.
func (u *MailKeySlotUpsertBulk) UpdateSlotType() *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateSlotType()
	})
}

// SetLabel sets the "label" field.
func (u *MailKeySlotUpsertBulk) SetLabel(v string) *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *MailKeySlotUpsertBulk) UpdateLabel() *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateLabel()
	})
}

// SetVersion sets the "version" field.
func (u *MailKeySlotUpsertBulk) SetVersion(v int) *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *MailKeySlotUpsertBulk) AddVersion(v int) *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *MailKeySlotUpsertBulk) UpdateVersion() *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateVersion()
	})
}

// SetWrappedKey sets the "wrapped_key" field.
func (u *MailKeySlotUpsertBulk) SetWrappedKey(v []byte) *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetWrappedKey(v)
	})
}

// UpdateWrappedKey sets the "wrapped_key" field to the value that was provided on create.
func (u *MailKeySlotUpsertBulk) UpdateWrappedKey() *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateWrappedKey()
	})
}

// SetNonce sets the "nonce" field.
func (u *MailKeySlotUpsertBulk) SetNonce(v []byte) *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *MailKeySlotUpsertBulk) UpdateNonce() *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateNonce()
	})
}

// SetKdfSalt sets the "kdf_salt" field.
func (u *MailKeySlotUpsertBulk) SetKdfSalt(v []byte) *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetKdfSalt(v)
	})
}

// UpdateKdfSalt sets the "kdf_salt" field to the value that was provided on create.
func (u *MailKeySlotUpsertBulk) UpdateKdfSalt() *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdateKdfSalt()
	})
}

// SetPrfSalt sets the "prf_salt" field.
func (u *MailKeySlotUpsertBulk) SetPrfSalt(v []byte) *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.SetPrfSalt(v)
	})
}

// UpdatePrfSalt sets the "prf_salt" field to the value that was provided on create.
func (u *MailKeySlotUpsertBulk) UpdatePrfSalt() *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.UpdatePrfSalt()
	})
}

// ClearPrfSalt clears the value of the "prf_salt" field.
func (u *MailKeySlotUpsertBulk) ClearPrfSalt() *MailKeySlotUpsertBulk {
	return u.Update(func(s *MailKeySlotUpsert) {
		s.ClearPrfSalt()
	})
}

// Exec executes the query.
func (u *MailKeySlotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MailKeySlotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MailKeySlotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MailKeySlotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
