// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"naust/daemon/internal/store/ent/metricsample"
	"naust/daemon/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MetricSampleDelete is the builder for deleting a MetricSample entity.
type MetricSampleDelete struct {
	config
	hooks    []Hook
	mutation *MetricSampleMutation
}

// Where appends a list predicates to the MetricSampleDelete builder.
func (_d *MetricSampleDelete) Where(ps ...predicate.MetricSample) *MetricSampleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MetricSampleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MetricSampleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MetricSampleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(metricsample.Table, sqlgraph.NewFieldSpec(metricsample.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MetricSampleDeleteOne is the builder for deleting a single MetricSample entity.
type MetricSampleDeleteOne struct {
	_d *MetricSampleDelete
}

// Where appends a list predicates to the MetricSampleDelete builder.
func (_d *MetricSampleDeleteOne) Where(ps ...predicate.MetricSample) *MetricSampleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MetricSampleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{metricsample.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MetricSampleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
