// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/metricsample"
	"naust/daemon/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MetricSampleUpdate is the builder for updating MetricSample entities.
type MetricSampleUpdate struct {
	config
	hooks    []Hook
	mutation *MetricSampleMutation
}

// Where appends a list predicates to the MetricSampleUpdate builder.
func (_u *MetricSampleUpdate) Where(ps ...predicate.MetricSample) *MetricSampleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMetric sets the "metric" field.
func (_u *MetricSampleUpdate) SetMetric(v string) *MetricSampleUpdate {
	_u.mutation.SetMetric(v)
	return _u
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (_u *MetricSampleUpdate) SetNillableMetric(v *string) *MetricSampleUpdate {
	if v != nil {
		_u.SetMetric(*v)
	}
	return _u
}

// SetSampledAt sets the "sampled_at" field.
func (_u *MetricSampleUpdate) SetSampledAt(v time.Time) *MetricSampleUpdate {
	_u.mutation.SetSampledAt(v)
	return _u
}

// SetNillableSampledAt sets the "sampled_at" field if the given value is not nil.
func (_u *MetricSampleUpdate) SetNillableSampledAt(v *time.Time) *MetricSampleUpdate {
	if v != nil {
		_u.SetSampledAt(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *MetricSampleUpdate) SetValue(v float64) *MetricSampleUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *MetricSampleUpdate) SetNillableValue(v *float64) *MetricSampleUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *MetricSampleUpdate) AddValue(v float64) *MetricSampleUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// Mutation returns the MetricSampleMutation object of the builder.
func (_u *MetricSampleUpdate) Mutation() *MetricSampleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MetricSampleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MetricSampleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MetricSampleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MetricSampleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MetricSampleUpdate) check() error {
	if v, ok := _u.mutation.Metric(); ok {
		if err := metricsample.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "MetricSample.metric": %w`, err)}
		}
	}
	return nil
}

func (_u *MetricSampleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(metricsample.Table, metricsample.Columns, sqlgraph.NewFieldSpec(metricsample.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metric(); ok {
		_spec.SetField(metricsample.FieldMetric, field.TypeString, value)
	}
	if value, ok := _u.mutation.SampledAt(); ok {
		_spec.SetField(metricsample.FieldSampledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(metricsample.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(metricsample.FieldValue, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metricsample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MetricSampleUpdateOne is the builder for updating a single MetricSample entity.
type MetricSampleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MetricSampleMutation
}

// SetMetric sets the "metric" field.
func (_u *MetricSampleUpdateOne) SetMetric(v string) *MetricSampleUpdateOne {
	_u.mutation.SetMetric(v)
	return _u
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (_u *MetricSampleUpdateOne) SetNillableMetric(v *string) *MetricSampleUpdateOne {
	if v != nil {
		_u.SetMetric(*v)
	}
	return _u
}

// SetSampledAt sets the "sampled_at" field.
func (_u *MetricSampleUpdateOne) SetSampledAt(v time.Time) *MetricSampleUpdateOne {
	_u.mutation.SetSampledAt(v)
	return _u
}

// SetNillableSampledAt sets the "sampled_at" field if the given value is not nil.
func (_u *MetricSampleUpdateOne) SetNillableSampledAt(v *time.Time) *MetricSampleUpdateOne {
	if v != nil {
		_u.SetSampledAt(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *MetricSampleUpdateOne) SetValue(v float64) *MetricSampleUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *MetricSampleUpdateOne) SetNillableValue(v *float64) *MetricSampleUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *MetricSampleUpdateOne) AddValue(v float64) *MetricSampleUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// Mutation returns the MetricSampleMutation object of the builder.
func (_u *MetricSampleUpdateOne) Mutation() *MetricSampleMutation {
	return _u.mutation
}

// Where appends a list predicates to the MetricSampleUpdate builder.
func (_u *MetricSampleUpdateOne) Where(ps ...predicate.MetricSample) *MetricSampleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MetricSampleUpdateOne) Select(field string, fields ...string) *MetricSampleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MetricSample entity.
func (_u *MetricSampleUpdateOne) Save(ctx context.Context) (*MetricSample, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MetricSampleUpdateOne) SaveX(ctx context.Context) *MetricSample {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MetricSampleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MetricSampleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MetricSampleUpdateOne) check() error {
	if v, ok := _u.mutation.Metric(); ok {
		if err := metricsample.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "MetricSample.metric": %w`, err)}
		}
	}
	return nil
}

func (_u *MetricSampleUpdateOne) sqlSave(ctx context.Context) (_node *MetricSample, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(metricsample.Table, metricsample.Columns, sqlgraph.NewFieldSpec(metricsample.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MetricSample.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, metricsample.FieldID)
		for _, f := range fields {
			if !metricsample.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != metricsample.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metric(); ok {
		_spec.SetField(metricsample.FieldMetric, field.TypeString, value)
	}
	if value, ok := _u.mutation.SampledAt(); ok {
		_spec.SetField(metricsample.FieldSampledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(metricsample.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(metricsample.FieldValue, field.TypeFloat64, value)
	}
	_node = &MetricSample{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metricsample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
