// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/totpcredential"
	"naust/daemon/internal/store/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TOTPCredentialCreate is the builder for creating a TOTPCredential entity.
type TOTPCredentialCreate struct {
	config
	mutation *TOTPCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSecret sets the "secret" field.
func (_c *TOTPCredentialCreate) SetSecret(v string) *TOTPCredentialCreate {
	_c.mutation.SetSecret(v)
	return _c
}

// SetMruToken sets the "mru_token" field.
func (_c *TOTPCredentialCreate) SetMruToken(v string) *TOTPCredentialCreate {
	_c.mutation.SetMruToken(v)
	return _c
}

// SetNillableMruToken sets the "mru_token" field if the given value is not nil.
func (_c *TOTPCredentialCreate) SetNillableMruToken(v *string) *TOTPCredentialCreate {
	if v != nil {
		_c.SetMruToken(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *TOTPCredentialCreate) SetLabel(v string) *TOTPCredentialCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *TOTPCredentialCreate) SetNillableLabel(v *string) *TOTPCredentialCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TOTPCredentialCreate) SetCreatedAt(v time.Time) *TOTPCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TOTPCredentialCreate) SetNillableCreatedAt(v *time.Time) *TOTPCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *TOTPCredentialCreate) SetUserID(id int) *TOTPCredentialCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TOTPCredentialCreate) SetUser(v *User) *TOTPCredentialCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TOTPCredentialMutation object of the builder.
func (_c *TOTPCredentialCreate) Mutation() *TOTPCredentialMutation {
	return _c.mutation
}

// Save creates the TOTPCredential in the database.
func (_c *TOTPCredentialCreate) Save(ctx context.Context) (*TOTPCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TOTPCredentialCreate) SaveX(ctx context.Context) *TOTPCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TOTPCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TOTPCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TOTPCredentialCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := totpcredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TOTPCredentialCreate) check() error {
	if _, ok := _c.mutation.Secret(); !ok {
		return &ValidationError{Name: "secret", err: errors.New(`ent: missing required field "TOTPCredential.secret"`)}
	}
	if v, ok := _c.mutation.Secret(); ok {
		if err := totpcredential.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "TOTPCredential.secret": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TOTPCredential.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TOTPCredential.user"`)}
	}
	return nil
}

func (_c *TOTPCredentialCreate) sqlSave(ctx context.Context) (*TOTPCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TOTPCredentialCreate) createSpec() (*TOTPCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &TOTPCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(totpcredential.Table, sqlgraph.NewFieldSpec(totpcredential.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Secret(); ok {
		_spec.SetField(totpcredential.FieldSecret, field.TypeString, value)
		_node.Secret = value
	}
	if value, ok := _c.mutation.MruToken(); ok {
		_spec.SetField(totpcredential.FieldMruToken, field.TypeString, value)
		_node.MruToken = &value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(totpcredential.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(totpcredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpcredential.UserTable,
			Columns: []string{totpcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_totp_credentials = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TOTPCredential.Create().
//		SetSecret(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TOTPCredentialUpsert) {
//			SetSecret(v+v).
//		}).
//		Exec(ctx)
func (_c *TOTPCredentialCreate) OnConflict(opts ...sql.ConflictOption) *TOTPCredentialUpsertOne {
	_c.conflict = opts
	return &TOTPCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TOTPCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TOTPCredentialCreate) OnConflictColumns(columns ...string) *TOTPCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TOTPCredentialUpsertOne{
		create: _c,
	}
}

type (
	// TOTPCredentialUpsertOne is the builder for "upsert"-ing
	//  one TOTPCredential node.
	TOTPCredentialUpsertOne struct {
		create *TOTPCredentialCreate
	}

	// TOTPCredentialUpsert is the "OnConflict" setter.
	TOTPCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetSecret sets the "secret" field.
func (u *TOTPCredentialUpsert) SetSecret(v string) *TOTPCredentialUpsert {
	u.Set(totpcredential.FieldSecret, v)
	return u
}

// UpdateSecret sets the "secret" field to the value that was provided on create.
func (u *TOTPCredentialUpsert) UpdateSecret() *TOTPCredentialUpsert {
	u.SetExcluded(totpcredential.FieldSecret)
	return u
}

// SetMruToken sets the "mru_token" field.
func (u *TOTPCredentialUpsert) SetMruToken(v string) *TOTPCredentialUpsert {
	u.Set(totpcredential.FieldMruToken, v)
	return u
}

// UpdateMruToken sets the "mru_token" field to the value that was provided on create.
func (u *TOTPCredentialUpsert) UpdateMruToken() *TOTPCredentialUpsert {
	u.SetExcluded(totpcredential.FieldMruToken)
	return u
}

// ClearMruToken clears the value of the "mru_token" field.
func (u *TOTPCredentialUpsert) ClearMruToken() *TOTPCredentialUpsert {
	u.SetNull(totpcredential.FieldMruToken)
	return u
}

// SetLabel sets the "label" field.
func (u *TOTPCredentialUpsert) SetLabel(v string) *TOTPCredentialUpsert {
	u.Set(totpcredential.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *TOTPCredentialUpsert) UpdateLabel() *TOTPCredentialUpsert {
	u.SetExcluded(totpcredential.FieldLabel)
	return u
}

// ClearLabel clears the value of the "label" field.
func (u *TOTPCredentialUpsert) ClearLabel() *TOTPCredentialUpsert {
	u.SetNull(totpcredential.FieldLabel)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TOTPCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TOTPCredentialUpsertOne) UpdateNewValues() *TOTPCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(totpcredential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TOTPCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TOTPCredentialUpsertOne) Ignore() *TOTPCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TOTPCredentialUpsertOne) DoNothing() *TOTPCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TOTPCredentialCreate.OnConflict
// documentation for more info.
func (u *TOTPCredentialUpsertOne) Update(set func(*TOTPCredentialUpsert)) *TOTPCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TOTPCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetSecret sets the "secret" field.
func (u *TOTPCredentialUpsertOne) SetSecret(v string) *TOTPCredentialUpsertOne {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.SetSecret(v)
	})
}

// UpdateSecret sets the "secret" field to the value that was provided on create.
func (u *TOTPCredentialUpsertOne) UpdateSecret() *TOTPCredentialUpsertOne {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.UpdateSecret()
	})
}

// SetMruToken sets the "mru_token" field.
func (u *TOTPCredentialUpsertOne) SetMruToken(v string) *TOTPCredentialUpsertOne {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.SetMruToken(v)
	})
}

// UpdateMruToken sets the "mru_token" field to the value that was provided on create.
func (u *TOTPCredentialUpsertOne) UpdateMruToken() *TOTPCredentialUpsertOne {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.UpdateMruToken()
	})
}

// ClearMruToken clears the value of the "mru_token" field.
func (u *TOTPCredentialUpsertOne) ClearMruToken() *TOTPCredentialUpsertOne {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.ClearMruToken()
	})
}

// SetLabel sets the "label" field.
func (u *TOTPCredentialUpsertOne) SetLabel(v string) *TOTPCredentialUpsertOne {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *TOTPCredentialUpsertOne) UpdateLabel() *TOTPCredentialUpsertOne {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.UpdateLabel()
	})
}

// ClearLabel clears the value of the "label" field.
func (u *TOTPCredentialUpsertOne) ClearLabel() *TOTPCredentialUpsertOne {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.ClearLabel()
	})
}

// Exec executes the query.
func (u *TOTPCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TOTPCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TOTPCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TOTPCredentialUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TOTPCredentialUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TOTPCredentialCreateBulk is the builder for creating many TOTPCredential entities in bulk.
type TOTPCredentialCreateBulk struct {
	config
	err      error
	builders []*TOTPCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the TOTPCredential entities in the database.
func (_c *TOTPCredentialCreateBulk) Save(ctx context.Context) ([]*TOTPCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TOTPCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TOTPCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TOTPCredentialCreateBulk) SaveX(ctx context.Context) []*TOTPCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TOTPCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TOTPCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TOTPCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TOTPCredentialUpsert) {
//			SetSecret(v+v).
//		}).
//		Exec(ctx)
func (_c *TOTPCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *TOTPCredentialUpsertBulk {
	_c.conflict = opts
	return &TOTPCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TOTPCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TOTPCredentialCreateBulk) OnConflictColumns(columns ...string) *TOTPCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TOTPCredentialUpsertBulk{
		create: _c,
	}
}

// TOTPCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of TOTPCredential nodes.
type TOTPCredentialUpsertBulk struct {
	create *TOTPCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TOTPCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TOTPCredentialUpsertBulk) UpdateNewValues() *TOTPCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(totpcredential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TOTPCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TOTPCredentialUpsertBulk) Ignore() *TOTPCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TOTPCredentialUpsertBulk) DoNothing() *TOTPCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TOTPCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *TOTPCredentialUpsertBulk) Update(set func(*TOTPCredentialUpsert)) *TOTPCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TOTPCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetSecret sets the "secret" field.
func (u *TOTPCredentialUpsertBulk) SetSecret(v string) *TOTPCredentialUpsertBulk {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.SetSecret(v)
	})
}

// UpdateSecret sets the "secret" field to the value that was provided on create.
func (u *TOTPCredentialUpsertBulk) UpdateSecret() *TOTPCredentialUpsertBulk {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.UpdateSecret()
	})
}

// SetMruToken sets the "mru_token" field.
func (u *TOTPCredentialUpsertBulk) SetMruToken(v string) *TOTPCredentialUpsertBulk {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.SetMruToken(v)
	})
}

// UpdateMruToken sets the "mru_token" field to the value that was provided on create.
func (u *TOTPCredentialUpsertBulk) UpdateMruToken() *TOTPCredentialUpsertBulk {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.UpdateMruToken()
	})
}

// ClearMruToken clears the value of the "mru_token" field.
func (u *TOTPCredentialUpsertBulk) ClearMruToken() *TOTPCredentialUpsertBulk {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.ClearMruToken()
	})
}

// SetLabel sets the "label" field.
func (u *TOTPCredentialUpsertBulk) SetLabel(v string) *TOTPCredentialUpsertBulk {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *TOTPCredentialUpsertBulk) UpdateLabel() *TOTPCredentialUpsertBulk {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.UpdateLabel()
	})
}

// ClearLabel clears the value of the "label" field.
func (u *TOTPCredentialUpsertBulk) ClearLabel() *TOTPCredentialUpsertBulk {
	return u.Update(func(s *TOTPCredentialUpsert) {
		s.ClearLabel()
	})
}

// Exec executes the query.
func (u *TOTPCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TOTPCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TOTPCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TOTPCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
