// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/apitoken"
	"naust/daemon/internal/store/ent/encryptionsetup"
	"naust/daemon/internal/store/ent/mailkeyslot"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/session"
	"naust/daemon/internal/store/ent/tenant"
	"naust/daemon/internal/store/ent/totpcredential"
	"naust/daemon/internal/store/ent/user"
	"naust/daemon/internal/store/ent/webauthnchallenge"
	"naust/daemon/internal/store/ent/webauthncredential"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdate) SetRole(v user.Role) *UserUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRole(v *user.Role) *UserUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetQuotaBytes sets the "quota_bytes" field.
func (_u *UserUpdate) SetQuotaBytes(v int64) *UserUpdate {
	_u.mutation.ResetQuotaBytes()
	_u.mutation.SetQuotaBytes(v)
	return _u
}

// SetNillableQuotaBytes sets the "quota_bytes" field if the given value is not nil.
func (_u *UserUpdate) SetNillableQuotaBytes(v *int64) *UserUpdate {
	if v != nil {
		_u.SetQuotaBytes(*v)
	}
	return _u
}

// AddQuotaBytes adds value to the "quota_bytes" field.
func (_u *UserUpdate) AddQuotaBytes(v int64) *UserUpdate {
	_u.mutation.AddQuotaBytes(v)
	return _u
}

// SetHomeNode sets the "home_node" field.
func (_u *UserUpdate) SetHomeNode(v string) *UserUpdate {
	_u.mutation.SetHomeNode(v)
	return _u
}

// SetNillableHomeNode sets the "home_node" field if the given value is not nil.
func (_u *UserUpdate) SetNillableHomeNode(v *string) *UserUpdate {
	if v != nil {
		_u.SetHomeNode(*v)
	}
	return _u
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *UserUpdate) AddSessionIDs(ids ...int) *UserUpdate {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *UserUpdate) AddSessions(v ...*Session) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// AddAPITokenIDs adds the "api_tokens" edge to the APIToken entity by IDs.
func (_u *UserUpdate) AddAPITokenIDs(ids ...int) *UserUpdate {
	_u.mutation.AddAPITokenIDs(ids...)
	return _u
}

// AddAPITokens adds the "api_tokens" edges to the APIToken entity.
func (_u *UserUpdate) AddAPITokens(v ...*APIToken) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPITokenIDs(ids...)
}

// AddTotpCredentialIDs adds the "totp_credentials" edge to the TOTPCredential entity by IDs.
func (_u *UserUpdate) AddTotpCredentialIDs(ids ...int) *UserUpdate {
	_u.mutation.AddTotpCredentialIDs(ids...)
	return _u
}

// AddTotpCredentials adds the "totp_credentials" edges to the TOTPCredential entity.
func (_u *UserUpdate) AddTotpCredentials(v ...*TOTPCredential) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTotpCredentialIDs(ids...)
}

// AddWebauthnCredentialIDs adds the "webauthn_credentials" edge to the WebAuthnCredential entity by IDs.
func (_u *UserUpdate) AddWebauthnCredentialIDs(ids ...int) *UserUpdate {
	_u.mutation.AddWebauthnCredentialIDs(ids...)
	return _u
}

// AddWebauthnCredentials adds the "webauthn_credentials" edges to the WebAuthnCredential entity.
func (_u *UserUpdate) AddWebauthnCredentials(v ...*WebAuthnCredential) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWebauthnCredentialIDs(ids...)
}

// AddWebauthnChallengeIDs adds the "webauthn_challenges" edge to the WebAuthnChallenge entity by IDs.
func (_u *UserUpdate) AddWebauthnChallengeIDs(ids ...int) *UserUpdate {
	_u.mutation.AddWebauthnChallengeIDs(ids...)
	return _u
}

// AddWebauthnChallenges adds the "webauthn_challenges" edges to the WebAuthnChallenge entity.
func (_u *UserUpdate) AddWebauthnChallenges(v ...*WebAuthnChallenge) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWebauthnChallengeIDs(ids...)
}

// AddMailKeySlotIDs adds the "mail_key_slots" edge to the MailKeySlot entity by IDs.
func (_u *UserUpdate) AddMailKeySlotIDs(ids ...int) *UserUpdate {
	_u.mutation.AddMailKeySlotIDs(ids...)
	return _u
}

// AddMailKeySlots adds the "mail_key_slots" edges to the MailKeySlot entity.
func (_u *UserUpdate) AddMailKeySlots(v ...*MailKeySlot) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMailKeySlotIDs(ids...)
}

// AddEncryptionSetupIDs adds the "encryption_setups" edge to the EncryptionSetup entity by IDs.
func (_u *UserUpdate) AddEncryptionSetupIDs(ids ...int) *UserUpdate {
	_u.mutation.AddEncryptionSetupIDs(ids...)
	return _u
}

// AddEncryptionSetups adds the "encryption_setups" edges to the EncryptionSetup entity.
func (_u *UserUpdate) AddEncryptionSetups(v ...*EncryptionSetup) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEncryptionSetupIDs(ids...)
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *UserUpdate) SetTenantID(id int) *UserUpdate {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *UserUpdate) SetTenant(v *Tenant) *UserUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *UserUpdate) ClearSessions() *UserUpdate {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *UserUpdate) RemoveSessionIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *UserUpdate) RemoveSessions(v ...*Session) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// ClearAPITokens clears all "api_tokens" edges to the APIToken entity.
func (_u *UserUpdate) ClearAPITokens() *UserUpdate {
	_u.mutation.ClearAPITokens()
	return _u
}

// RemoveAPITokenIDs removes the "api_tokens" edge to APIToken entities by IDs.
func (_u *UserUpdate) RemoveAPITokenIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveAPITokenIDs(ids...)
	return _u
}

// RemoveAPITokens removes "api_tokens" edges to APIToken entities.
func (_u *UserUpdate) RemoveAPITokens(v ...*APIToken) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPITokenIDs(ids...)
}

// ClearTotpCredentials clears all "totp_credentials" edges to the TOTPCredential entity.
func (_u *UserUpdate) ClearTotpCredentials() *UserUpdate {
	_u.mutation.ClearTotpCredentials()
	return _u
}

// RemoveTotpCredentialIDs removes the "totp_credentials" edge to TOTPCredential entities by IDs.
func (_u *UserUpdate) RemoveTotpCredentialIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveTotpCredentialIDs(ids...)
	return _u
}

// RemoveTotpCredentials removes "totp_credentials" edges to TOTPCredential entities.
func (_u *UserUpdate) RemoveTotpCredentials(v ...*TOTPCredential) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTotpCredentialIDs(ids...)
}

// ClearWebauthnCredentials clears all "webauthn_credentials" edges to the WebAuthnCredential entity.
func (_u *UserUpdate) ClearWebauthnCredentials() *UserUpdate {
	_u.mutation.ClearWebauthnCredentials()
	return _u
}

// RemoveWebauthnCredentialIDs removes the "webauthn_credentials" edge to WebAuthnCredential entities by IDs.
func (_u *UserUpdate) RemoveWebauthnCredentialIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveWebauthnCredentialIDs(ids...)
	return _u
}

// RemoveWebauthnCredentials removes "webauthn_credentials" edges to WebAuthnCredential entities.
func (_u *UserUpdate) RemoveWebauthnCredentials(v ...*WebAuthnCredential) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWebauthnCredentialIDs(ids...)
}

// ClearWebauthnChallenges clears all "webauthn_challenges" edges to the WebAuthnChallenge entity.
func (_u *UserUpdate) ClearWebauthnChallenges() *UserUpdate {
	_u.mutation.ClearWebauthnChallenges()
	return _u
}

// RemoveWebauthnChallengeIDs removes the "webauthn_challenges" edge to WebAuthnChallenge entities by IDs.
func (_u *UserUpdate) RemoveWebauthnChallengeIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveWebauthnChallengeIDs(ids...)
	return _u
}

// RemoveWebauthnChallenges removes "webauthn_challenges" edges to WebAuthnChallenge entities.
func (_u *UserUpdate) RemoveWebauthnChallenges(v ...*WebAuthnChallenge) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWebauthnChallengeIDs(ids...)
}

// ClearMailKeySlots clears all "mail_key_slots" edges to the MailKeySlot entity.
func (_u *UserUpdate) ClearMailKeySlots() *UserUpdate {
	_u.mutation.ClearMailKeySlots()
	return _u
}

// RemoveMailKeySlotIDs removes the "mail_key_slots" edge to MailKeySlot entities by IDs.
func (_u *UserUpdate) RemoveMailKeySlotIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveMailKeySlotIDs(ids...)
	return _u
}

// RemoveMailKeySlots removes "mail_key_slots" edges to MailKeySlot entities.
func (_u *UserUpdate) RemoveMailKeySlots(v ...*MailKeySlot) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMailKeySlotIDs(ids...)
}

// ClearEncryptionSetups clears all "encryption_setups" edges to the EncryptionSetup entity.
func (_u *UserUpdate) ClearEncryptionSetups() *UserUpdate {
	_u.mutation.ClearEncryptionSetups()
	return _u
}

// RemoveEncryptionSetupIDs removes the "encryption_setups" edge to EncryptionSetup entities by IDs.
func (_u *UserUpdate) RemoveEncryptionSetupIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveEncryptionSetupIDs(ids...)
	return _u
}

// RemoveEncryptionSetups removes "encryption_setups" edges to EncryptionSetup entities.
func (_u *UserUpdate) RemoveEncryptionSetups(v ...*EncryptionSetup) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEncryptionSetupIDs(ids...)
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *UserUpdate) ClearTenant() *UserUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaBytes(); ok {
		if err := user.QuotaBytesValidator(v); err != nil {
			return &ValidationError{Name: "quota_bytes", err: fmt.Errorf(`ent: validator failed for field "User.quota_bytes": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "User.tenant"`)
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.QuotaBytes(); ok {
		_spec.SetField(user.FieldQuotaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaBytes(); ok {
		_spec.AddField(user.FieldQuotaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.HomeNode(); ok {
		_spec.SetField(user.FieldHomeNode, field.TypeString, value)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APITokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.APITokensTable,
			Columns: []string{user.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPITokensIDs(); len(nodes) > 0 && !_u.mutation.APITokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.APITokensTable,
			Columns: []string{user.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APITokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.APITokensTable,
			Columns: []string{user.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TotpCredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TotpCredentialsTable,
			Columns: []string{user.TotpCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(totpcredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTotpCredentialsIDs(); len(nodes) > 0 && !_u.mutation.TotpCredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TotpCredentialsTable,
			Columns: []string{user.TotpCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(totpcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TotpCredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TotpCredentialsTable,
			Columns: []string{user.TotpCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(totpcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WebauthnCredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnCredentialsTable,
			Columns: []string{user.WebauthnCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWebauthnCredentialsIDs(); len(nodes) > 0 && !_u.mutation.WebauthnCredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnCredentialsTable,
			Columns: []string{user.WebauthnCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WebauthnCredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnCredentialsTable,
			Columns: []string{user.WebauthnCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WebauthnChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnChallengesTable,
			Columns: []string{user.WebauthnChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthnchallenge.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWebauthnChallengesIDs(); len(nodes) > 0 && !_u.mutation.WebauthnChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnChallengesTable,
			Columns: []string{user.WebauthnChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthnchallenge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WebauthnChallengesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnChallengesTable,
			Columns: []string{user.WebauthnChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthnchallenge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MailKeySlotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MailKeySlotsTable,
			Columns: []string{user.MailKeySlotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mailkeyslot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMailKeySlotsIDs(); len(nodes) > 0 && !_u.mutation.MailKeySlotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MailKeySlotsTable,
			Columns: []string{user.MailKeySlotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mailkeyslot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MailKeySlotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MailKeySlotsTable,
			Columns: []string{user.MailKeySlotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mailkeyslot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EncryptionSetupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.EncryptionSetupsTable,
			Columns: []string{user.EncryptionSetupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(encryptionsetup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEncryptionSetupsIDs(); len(nodes) > 0 && !_u.mutation.EncryptionSetupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.EncryptionSetupsTable,
			Columns: []string{user.EncryptionSetupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(encryptionsetup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EncryptionSetupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.EncryptionSetupsTable,
			Columns: []string{user.EncryptionSetupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(encryptionsetup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.TenantTable,
			Columns: []string{user.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.TenantTable,
			Columns: []string{user.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdateOne) SetRole(v user.Role) *UserUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRole(v *user.Role) *UserUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetQuotaBytes sets the "quota_bytes" field.
func (_u *UserUpdateOne) SetQuotaBytes(v int64) *UserUpdateOne {
	_u.mutation.ResetQuotaBytes()
	_u.mutation.SetQuotaBytes(v)
	return _u
}

// SetNillableQuotaBytes sets the "quota_bytes" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableQuotaBytes(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetQuotaBytes(*v)
	}
	return _u
}

// AddQuotaBytes adds value to the "quota_bytes" field.
func (_u *UserUpdateOne) AddQuotaBytes(v int64) *UserUpdateOne {
	_u.mutation.AddQuotaBytes(v)
	return _u
}

// SetHomeNode sets the "home_node" field.
func (_u *UserUpdateOne) SetHomeNode(v string) *UserUpdateOne {
	_u.mutation.SetHomeNode(v)
	return _u
}

// SetNillableHomeNode sets the "home_node" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableHomeNode(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetHomeNode(*v)
	}
	return _u
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *UserUpdateOne) AddSessionIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *UserUpdateOne) AddSessions(v ...*Session) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// AddAPITokenIDs adds the "api_tokens" edge to the APIToken entity by IDs.
func (_u *UserUpdateOne) AddAPITokenIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddAPITokenIDs(ids...)
	return _u
}

// AddAPITokens adds the "api_tokens" edges to the APIToken entity.
func (_u *UserUpdateOne) AddAPITokens(v ...*APIToken) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPITokenIDs(ids...)
}

// AddTotpCredentialIDs adds the "totp_credentials" edge to the TOTPCredential entity by IDs.
func (_u *UserUpdateOne) AddTotpCredentialIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddTotpCredentialIDs(ids...)
	return _u
}

// AddTotpCredentials adds the "totp_credentials" edges to the TOTPCredential entity.
func (_u *UserUpdateOne) AddTotpCredentials(v ...*TOTPCredential) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTotpCredentialIDs(ids...)
}

// AddWebauthnCredentialIDs adds the "webauthn_credentials" edge to the WebAuthnCredential entity by IDs.
func (_u *UserUpdateOne) AddWebauthnCredentialIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddWebauthnCredentialIDs(ids...)
	return _u
}

// AddWebauthnCredentials adds the "webauthn_credentials" edges to the WebAuthnCredential entity.
func (_u *UserUpdateOne) AddWebauthnCredentials(v ...*WebAuthnCredential) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWebauthnCredentialIDs(ids...)
}

// AddWebauthnChallengeIDs adds the "webauthn_challenges" edge to the WebAuthnChallenge entity by IDs.
func (_u *UserUpdateOne) AddWebauthnChallengeIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddWebauthnChallengeIDs(ids...)
	return _u
}

// AddWebauthnChallenges adds the "webauthn_challenges" edges to the WebAuthnChallenge entity.
func (_u *UserUpdateOne) AddWebauthnChallenges(v ...*WebAuthnChallenge) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWebauthnChallengeIDs(ids...)
}

// AddMailKeySlotIDs adds the "mail_key_slots" edge to the MailKeySlot entity by IDs.
func (_u *UserUpdateOne) AddMailKeySlotIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddMailKeySlotIDs(ids...)
	return _u
}

// AddMailKeySlots adds the "mail_key_slots" edges to the MailKeySlot entity.
func (_u *UserUpdateOne) AddMailKeySlots(v ...*MailKeySlot) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMailKeySlotIDs(ids...)
}

// AddEncryptionSetupIDs adds the "encryption_setups" edge to the EncryptionSetup entity by IDs.
func (_u *UserUpdateOne) AddEncryptionSetupIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddEncryptionSetupIDs(ids...)
	return _u
}

// AddEncryptionSetups adds the "encryption_setups" edges to the EncryptionSetup entity.
func (_u *UserUpdateOne) AddEncryptionSetups(v ...*EncryptionSetup) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEncryptionSetupIDs(ids...)
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *UserUpdateOne) SetTenantID(id int) *UserUpdateOne {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *UserUpdateOne) SetTenant(v *Tenant) *UserUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *UserUpdateOne) ClearSessions() *UserUpdateOne {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *UserUpdateOne) RemoveSessionIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *UserUpdateOne) RemoveSessions(v ...*Session) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// ClearAPITokens clears all "api_tokens" edges to the APIToken entity.
func (_u *UserUpdateOne) ClearAPITokens() *UserUpdateOne {
	_u.mutation.ClearAPITokens()
	return _u
}

// RemoveAPITokenIDs removes the "api_tokens" edge to APIToken entities by IDs.
func (_u *UserUpdateOne) RemoveAPITokenIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveAPITokenIDs(ids...)
	return _u
}

// RemoveAPITokens removes "api_tokens" edges to APIToken entities.
func (_u *UserUpdateOne) RemoveAPITokens(v ...*APIToken) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPITokenIDs(ids...)
}

// ClearTotpCredentials clears all "totp_credentials" edges to the TOTPCredential entity.
func (_u *UserUpdateOne) ClearTotpCredentials() *UserUpdateOne {
	_u.mutation.ClearTotpCredentials()
	return _u
}

// RemoveTotpCredentialIDs removes the "totp_credentials" edge to TOTPCredential entities by IDs.
func (_u *UserUpdateOne) RemoveTotpCredentialIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveTotpCredentialIDs(ids...)
	return _u
}

// RemoveTotpCredentials removes "totp_credentials" edges to TOTPCredential entities.
func (_u *UserUpdateOne) RemoveTotpCredentials(v ...*TOTPCredential) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTotpCredentialIDs(ids...)
}

// ClearWebauthnCredentials clears all "webauthn_credentials" edges to the WebAuthnCredential entity.
func (_u *UserUpdateOne) ClearWebauthnCredentials() *UserUpdateOne {
	_u.mutation.ClearWebauthnCredentials()
	return _u
}

// RemoveWebauthnCredentialIDs removes the "webauthn_credentials" edge to WebAuthnCredential entities by IDs.
func (_u *UserUpdateOne) RemoveWebauthnCredentialIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveWebauthnCredentialIDs(ids...)
	return _u
}

// RemoveWebauthnCredentials removes "webauthn_credentials" edges to WebAuthnCredential entities.
func (_u *UserUpdateOne) RemoveWebauthnCredentials(v ...*WebAuthnCredential) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWebauthnCredentialIDs(ids...)
}

// ClearWebauthnChallenges clears all "webauthn_challenges" edges to the WebAuthnChallenge entity.
func (_u *UserUpdateOne) ClearWebauthnChallenges() *UserUpdateOne {
	_u.mutation.ClearWebauthnChallenges()
	return _u
}

// RemoveWebauthnChallengeIDs removes the "webauthn_challenges" edge to WebAuthnChallenge entities by IDs.
func (_u *UserUpdateOne) RemoveWebauthnChallengeIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveWebauthnChallengeIDs(ids...)
	return _u
}

// RemoveWebauthnChallenges removes "webauthn_challenges" edges to WebAuthnChallenge entities.
func (_u *UserUpdateOne) RemoveWebauthnChallenges(v ...*WebAuthnChallenge) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWebauthnChallengeIDs(ids...)
}

// ClearMailKeySlots clears all "mail_key_slots" edges to the MailKeySlot entity.
func (_u *UserUpdateOne) ClearMailKeySlots() *UserUpdateOne {
	_u.mutation.ClearMailKeySlots()
	return _u
}

// RemoveMailKeySlotIDs removes the "mail_key_slots" edge to MailKeySlot entities by IDs.
func (_u *UserUpdateOne) RemoveMailKeySlotIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveMailKeySlotIDs(ids...)
	return _u
}

// RemoveMailKeySlots removes "mail_key_slots" edges to MailKeySlot entities.
func (_u *UserUpdateOne) RemoveMailKeySlots(v ...*MailKeySlot) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMailKeySlotIDs(ids...)
}

// ClearEncryptionSetups clears all "encryption_setups" edges to the EncryptionSetup entity.
func (_u *UserUpdateOne) ClearEncryptionSetups() *UserUpdateOne {
	_u.mutation.ClearEncryptionSetups()
	return _u
}

// RemoveEncryptionSetupIDs removes the "encryption_setups" edge to EncryptionSetup entities by IDs.
func (_u *UserUpdateOne) RemoveEncryptionSetupIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveEncryptionSetupIDs(ids...)
	return _u
}

// RemoveEncryptionSetups removes "encryption_setups" edges to EncryptionSetup entities.
func (_u *UserUpdateOne) RemoveEncryptionSetups(v ...*EncryptionSetup) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEncryptionSetupIDs(ids...)
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *UserUpdateOne) ClearTenant() *UserUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaBytes(); ok {
		if err := user.QuotaBytesValidator(v); err != nil {
			return &ValidationError{Name: "quota_bytes", err: fmt.Errorf(`ent: validator failed for field "User.quota_bytes": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "User.tenant"`)
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.QuotaBytes(); ok {
		_spec.SetField(user.FieldQuotaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaBytes(); ok {
		_spec.AddField(user.FieldQuotaBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.HomeNode(); ok {
		_spec.SetField(user.FieldHomeNode, field.TypeString, value)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APITokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.APITokensTable,
			Columns: []string{user.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPITokensIDs(); len(nodes) > 0 && !_u.mutation.APITokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.APITokensTable,
			Columns: []string{user.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APITokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.APITokensTable,
			Columns: []string{user.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TotpCredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TotpCredentialsTable,
			Columns: []string{user.TotpCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(totpcredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTotpCredentialsIDs(); len(nodes) > 0 && !_u.mutation.TotpCredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TotpCredentialsTable,
			Columns: []string{user.TotpCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(totpcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TotpCredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TotpCredentialsTable,
			Columns: []string{user.TotpCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(totpcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WebauthnCredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnCredentialsTable,
			Columns: []string{user.WebauthnCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWebauthnCredentialsIDs(); len(nodes) > 0 && !_u.mutation.WebauthnCredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnCredentialsTable,
			Columns: []string{user.WebauthnCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WebauthnCredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnCredentialsTable,
			Columns: []string{user.WebauthnCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WebauthnChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnChallengesTable,
			Columns: []string{user.WebauthnChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthnchallenge.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWebauthnChallengesIDs(); len(nodes) > 0 && !_u.mutation.WebauthnChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnChallengesTable,
			Columns: []string{user.WebauthnChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthnchallenge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WebauthnChallengesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WebauthnChallengesTable,
			Columns: []string{user.WebauthnChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthnchallenge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MailKeySlotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MailKeySlotsTable,
			Columns: []string{user.MailKeySlotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mailkeyslot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMailKeySlotsIDs(); len(nodes) > 0 && !_u.mutation.MailKeySlotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MailKeySlotsTable,
			Columns: []string{user.MailKeySlotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mailkeyslot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MailKeySlotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MailKeySlotsTable,
			Columns: []string{user.MailKeySlotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mailkeyslot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EncryptionSetupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.EncryptionSetupsTable,
			Columns: []string{user.EncryptionSetupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(encryptionsetup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEncryptionSetupsIDs(); len(nodes) > 0 && !_u.mutation.EncryptionSetupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.EncryptionSetupsTable,
			Columns: []string{user.EncryptionSetupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(encryptionsetup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EncryptionSetupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.EncryptionSetupsTable,
			Columns: []string{user.EncryptionSetupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(encryptionsetup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.TenantTable,
			Columns: []string{user.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.TenantTable,
			Columns: []string{user.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
