// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/user"
	"naust/daemon/internal/store/ent/webauthncredential"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebAuthnCredentialCreate is the builder for creating a WebAuthnCredential entity.
type WebAuthnCredentialCreate struct {
	config
	mutation *WebAuthnCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCredentialID sets the "credential_id" field.
func (_c *WebAuthnCredentialCreate) SetCredentialID(v []byte) *WebAuthnCredentialCreate {
	_c.mutation.SetCredentialID(v)
	return _c
}

// SetData sets the "data" field.
func (_c *WebAuthnCredentialCreate) SetData(v string) *WebAuthnCredentialCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetName sets the "name" field.
func (_c *WebAuthnCredentialCreate) SetName(v string) *WebAuthnCredentialCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *WebAuthnCredentialCreate) SetNillableName(v *string) *WebAuthnCredentialCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebAuthnCredentialCreate) SetCreatedAt(v time.Time) *WebAuthnCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebAuthnCredentialCreate) SetNillableCreatedAt(v *time.Time) *WebAuthnCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetLastUsed sets the "last_used" field.
func (_c *WebAuthnCredentialCreate) SetLastUsed(v time.Time) *WebAuthnCredentialCreate {
	_c.mutation.SetLastUsed(v)
	return _c
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (_c *WebAuthnCredentialCreate) SetNillableLastUsed(v *time.Time) *WebAuthnCredentialCreate {
	if v != nil {
		_c.SetLastUsed(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *WebAuthnCredentialCreate) SetUserID(id int) *WebAuthnCredentialCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *WebAuthnCredentialCreate) SetUser(v *User) *WebAuthnCredentialCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the WebAuthnCredentialMutation object of the builder.
func (_c *WebAuthnCredentialCreate) Mutation() *WebAuthnCredentialMutation {
	return _c.mutation
}

// Save creates the WebAuthnCredential in the database.
func (_c *WebAuthnCredentialCreate) Save(ctx context.Context) (*WebAuthnCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebAuthnCredentialCreate) SaveX(ctx context.Context) *WebAuthnCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebAuthnCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebAuthnCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebAuthnCredentialCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webauthncredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebAuthnCredentialCreate) check() error {
	if _, ok := _c.mutation.CredentialID(); !ok {
		return &ValidationError{Name: "credential_id", err: errors.New(`ent: missing required field "WebAuthnCredential.credential_id"`)}
	}
	if v, ok := _c.mutation.CredentialID(); ok {
		if err := webauthncredential.CredentialIDValidator(v); err != nil {
			return &ValidationError{Name: "credential_id", err: fmt.Errorf(`ent: validator failed for field "WebAuthnCredential.credential_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "WebAuthnCredential.data"`)}
	}
	if v, ok := _c.mutation.Data(); ok {
		if err := webauthncredential.DataValidator(v); err != nil {
			return &ValidationError{Name: "data", err: fmt.Errorf(`ent: validator failed for field "WebAuthnCredential.data": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebAuthnCredential.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "WebAuthnCredential.user"`)}
	}
	return nil
}

func (_c *WebAuthnCredentialCreate) sqlSave(ctx context.Context) (*WebAuthnCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebAuthnCredentialCreate) createSpec() (*WebAuthnCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &WebAuthnCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webauthncredential.Table, sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CredentialID(); ok {
		_spec.SetField(webauthncredential.FieldCredentialID, field.TypeBytes, value)
		_node.CredentialID = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(webauthncredential.FieldData, field.TypeString, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(webauthncredential.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webauthncredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastUsed(); ok {
		_spec.SetField(webauthncredential.FieldLastUsed, field.TypeTime, value)
		_node.LastUsed = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webauthncredential.UserTable,
			Columns: []string{webauthncredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_webauthn_credentials = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebAuthnCredential.Create().
//		SetCredentialID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebAuthnCredentialUpsert) {
//			SetCredentialID(v+v).
//		}).
//		Exec(ctx)
func (_c *WebAuthnCredentialCreate) OnConflict(opts ...sql.ConflictOption) *WebAuthnCredentialUpsertOne {
	_c.conflict = opts
	return &WebAuthnCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebAuthnCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebAuthnCredentialCreate) OnConflictColumns(columns ...string) *WebAuthnCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebAuthnCredentialUpsertOne{
		create: _c,
	}
}

type (
	// WebAuthnCredentialUpsertOne is the builder for "upsert"-ing
	//  one WebAuthnCredential node.
	WebAuthnCredentialUpsertOne struct {
		create *WebAuthnCredentialCreate
	}

	// WebAuthnCredentialUpsert is the "OnConflict" setter.
	WebAuthnCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetCredentialID sets the "credential_id" field.
func (u *WebAuthnCredentialUpsert) SetCredentialID(v []byte) *WebAuthnCredentialUpsert {
	u.Set(webauthncredential.FieldCredentialID, v)
	return u
}

// UpdateCredentialID sets the "credential_id" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsert) UpdateCredentialID() *WebAuthnCredentialUpsert {
	u.SetExcluded(webauthncredential.FieldCredentialID)
	return u
}

// SetData sets the "data" field.
func (u *WebAuthnCredentialUpsert) SetData(v string) *WebAuthnCredentialUpsert {
	u.Set(webauthncredential.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsert) UpdateData() *WebAuthnCredentialUpsert {
	u.SetExcluded(webauthncredential.FieldData)
	return u
}

// SetName sets the "name" field.
func (u *WebAuthnCredentialUpsert) SetName(v string) *WebAuthnCredentialUpsert {
	u.Set(webauthncredential.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsert) UpdateName() *WebAuthnCredentialUpsert {
	u.SetExcluded(webauthncredential.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *WebAuthnCredentialUpsert) ClearName() *WebAuthnCredentialUpsert {
	u.SetNull(webauthncredential.FieldName)
	return u
}

// SetLastUsed sets the "last_used" field.
func (u *WebAuthnCredentialUpsert) SetLastUsed(v time.Time) *WebAuthnCredentialUpsert {
	u.Set(webauthncredential.FieldLastUsed, v)
	return u
}

// UpdateLastUsed sets the "last_used" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsert) UpdateLastUsed() *WebAuthnCredentialUpsert {
	u.SetExcluded(webauthncredential.FieldLastUsed)
	return u
}

// ClearLastUsed clears the value of the "last_used" field.
func (u *WebAuthnCredentialUpsert) ClearLastUsed() *WebAuthnCredentialUpsert {
	u.SetNull(webauthncredential.FieldLastUsed)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WebAuthnCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebAuthnCredentialUpsertOne) UpdateNewValues() *WebAuthnCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(webauthncredential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebAuthnCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WebAuthnCredentialUpsertOne) Ignore() *WebAuthnCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebAuthnCredentialUpsertOne) DoNothing() *WebAuthnCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebAuthnCredentialCreate.OnConflict
// documentation for more info.
func (u *WebAuthnCredentialUpsertOne) Update(set func(*WebAuthnCredentialUpsert)) *WebAuthnCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebAuthnCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetCredentialID sets the "credential_id" field.
func (u *WebAuthnCredentialUpsertOne) SetCredentialID(v []byte) *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.SetCredentialID(v)
	})
}

// UpdateCredentialID sets the "credential_id" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsertOne) UpdateCredentialID() *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.UpdateCredentialID()
	})
}

// SetData sets the "data" field.
func (u *WebAuthnCredentialUpsertOne) SetData(v string) *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsertOne) UpdateData() *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.UpdateData()
	})
}

// SetName sets the "name" field.
func (u *WebAuthnCredentialUpsertOne) SetName(v string) *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsertOne) UpdateName() *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *WebAuthnCredentialUpsertOne) ClearName() *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.ClearName()
	})
}

// SetLastUsed sets the "last_used" field.
func (u *WebAuthnCredentialUpsertOne) SetLastUsed(v time.Time) *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.SetLastUsed(v)
	})
}

// UpdateLastUsed sets the "last_used" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsertOne) UpdateLastUsed() *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.UpdateLastUsed()
	})
}

// ClearLastUsed clears the value of the "last_used" field.
func (u *WebAuthnCredentialUpsertOne) ClearLastUsed() *WebAuthnCredentialUpsertOne {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.ClearLastUsed()
	})
}

// Exec executes the query.
func (u *WebAuthnCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebAuthnCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebAuthnCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WebAuthnCredentialUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WebAuthnCredentialUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WebAuthnCredentialCreateBulk is the builder for creating many WebAuthnCredential entities in bulk.
type WebAuthnCredentialCreateBulk struct {
	config
	err      error
	builders []*WebAuthnCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the WebAuthnCredential entities in the database.
func (_c *WebAuthnCredentialCreateBulk) Save(ctx context.Context) ([]*WebAuthnCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebAuthnCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebAuthnCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebAuthnCredentialCreateBulk) SaveX(ctx context.Context) []*WebAuthnCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebAuthnCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebAuthnCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebAuthnCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebAuthnCredentialUpsert) {
//			SetCredentialID(v+v).
//		}).
//		Exec(ctx)
func (_c *WebAuthnCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *WebAuthnCredentialUpsertBulk {
	_c.conflict = opts
	return &WebAuthnCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebAuthnCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebAuthnCredentialCreateBulk) OnConflictColumns(columns ...string) *WebAuthnCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebAuthnCredentialUpsertBulk{
		create: _c,
	}
}

// WebAuthnCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of WebAuthnCredential nodes.
type WebAuthnCredentialUpsertBulk struct {
	create *WebAuthnCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WebAuthnCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebAuthnCredentialUpsertBulk) UpdateNewValues() *WebAuthnCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(webauthncredential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebAuthnCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WebAuthnCredentialUpsertBulk) Ignore() *WebAuthnCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebAuthnCredentialUpsertBulk) DoNothing() *WebAuthnCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebAuthnCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *WebAuthnCredentialUpsertBulk) Update(set func(*WebAuthnCredentialUpsert)) *WebAuthnCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebAuthnCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetCredentialID sets the "credential_id" field.
func (u *WebAuthnCredentialUpsertBulk) SetCredentialID(v []byte) *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.SetCredentialID(v)
	})
}

// UpdateCredentialID sets the "credential_id" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsertBulk) UpdateCredentialID() *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.UpdateCredentialID()
	})
}

// SetData sets the "data" field.
func (u *WebAuthnCredentialUpsertBulk) SetData(v string) *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsertBulk) UpdateData() *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.UpdateData()
	})
}

// SetName sets the "name" field.
func (u *WebAuthnCredentialUpsertBulk) SetName(v string) *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsertBulk) UpdateName() *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *WebAuthnCredentialUpsertBulk) ClearName() *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.ClearName()
	})
}

// SetLastUsed sets the "last_used" field.
func (u *WebAuthnCredentialUpsertBulk) SetLastUsed(v time.Time) *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.SetLastUsed(v)
	})
}

// UpdateLastUsed sets the "last_used" field to the value that was provided on create.
func (u *WebAuthnCredentialUpsertBulk) UpdateLastUsed() *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.UpdateLastUsed()
	})
}

// ClearLastUsed clears the value of the "last_used" field.
func (u *WebAuthnCredentialUpsertBulk) ClearLastUsed() *WebAuthnCredentialUpsertBulk {
	return u.Update(func(s *WebAuthnCredentialUpsert) {
		s.ClearLastUsed()
	})
}

// Exec executes the query.
func (u *WebAuthnCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WebAuthnCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebAuthnCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebAuthnCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
