// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/user"
	"naust/daemon/internal/store/ent/webauthncredential"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebAuthnCredentialUpdate is the builder for updating WebAuthnCredential entities.
type WebAuthnCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *WebAuthnCredentialMutation
}

// Where appends a list predicates to the WebAuthnCredentialUpdate builder.
func (_u *WebAuthnCredentialUpdate) Where(ps ...predicate.WebAuthnCredential) *WebAuthnCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCredentialID sets the "credential_id" field.
func (_u *WebAuthnCredentialUpdate) SetCredentialID(v []byte) *WebAuthnCredentialUpdate {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetData sets the "data" field.
func (_u *WebAuthnCredentialUpdate) SetData(v string) *WebAuthnCredentialUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetNillableData sets the "data" field if the given value is not nil.
func (_u *WebAuthnCredentialUpdate) SetNillableData(v *string) *WebAuthnCredentialUpdate {
	if v != nil {
		_u.SetData(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WebAuthnCredentialUpdate) SetName(v string) *WebAuthnCredentialUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WebAuthnCredentialUpdate) SetNillableName(v *string) *WebAuthnCredentialUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *WebAuthnCredentialUpdate) ClearName() *WebAuthnCredentialUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetLastUsed sets the "last_used" field.
func (_u *WebAuthnCredentialUpdate) SetLastUsed(v time.Time) *WebAuthnCredentialUpdate {
	_u.mutation.SetLastUsed(v)
	return _u
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (_u *WebAuthnCredentialUpdate) SetNillableLastUsed(v *time.Time) *WebAuthnCredentialUpdate {
	if v != nil {
		_u.SetLastUsed(*v)
	}
	return _u
}

// ClearLastUsed clears the value of the "last_used" field.
func (_u *WebAuthnCredentialUpdate) ClearLastUsed() *WebAuthnCredentialUpdate {
	_u.mutation.ClearLastUsed()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *WebAuthnCredentialUpdate) SetUserID(id int) *WebAuthnCredentialUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WebAuthnCredentialUpdate) SetUser(v *User) *WebAuthnCredentialUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WebAuthnCredentialMutation object of the builder.
func (_u *WebAuthnCredentialUpdate) Mutation() *WebAuthnCredentialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WebAuthnCredentialUpdate) ClearUser() *WebAuthnCredentialUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebAuthnCredentialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebAuthnCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebAuthnCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebAuthnCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebAuthnCredentialUpdate) check() error {
	if v, ok := _u.mutation.CredentialID(); ok {
		if err := webauthncredential.CredentialIDValidator(v); err != nil {
			return &ValidationError{Name: "credential_id", err: fmt.Errorf(`ent: validator failed for field "WebAuthnCredential.credential_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Data(); ok {
		if err := webauthncredential.DataValidator(v); err != nil {
			return &ValidationError{Name: "data", err: fmt.Errorf(`ent: validator failed for field "WebAuthnCredential.data": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebAuthnCredential.user"`)
	}
	return nil
}

func (_u *WebAuthnCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webauthncredential.Table, webauthncredential.Columns, sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(webauthncredential.FieldCredentialID, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(webauthncredential.FieldData, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(webauthncredential.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(webauthncredential.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.LastUsed(); ok {
		_spec.SetField(webauthncredential.FieldLastUsed, field.TypeTime, value)
	}
	if _u.mutation.LastUsedCleared() {
		_spec.ClearField(webauthncredential.FieldLastUsed, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webauthncredential.UserTable,
			Columns: []string{webauthncredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webauthncredential.UserTable,
			Columns: []string{webauthncredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webauthncredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebAuthnCredentialUpdateOne is the builder for updating a single WebAuthnCredential entity.
type WebAuthnCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebAuthnCredentialMutation
}

// SetCredentialID sets the "credential_id" field.
func (_u *WebAuthnCredentialUpdateOne) SetCredentialID(v []byte) *WebAuthnCredentialUpdateOne {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetData sets the "data" field.
func (_u *WebAuthnCredentialUpdateOne) SetData(v string) *WebAuthnCredentialUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetNillableData sets the "data" field if the given value is not nil.
func (_u *WebAuthnCredentialUpdateOne) SetNillableData(v *string) *WebAuthnCredentialUpdateOne {
	if v != nil {
		_u.SetData(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WebAuthnCredentialUpdateOne) SetName(v string) *WebAuthnCredentialUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WebAuthnCredentialUpdateOne) SetNillableName(v *string) *WebAuthnCredentialUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *WebAuthnCredentialUpdateOne) ClearName() *WebAuthnCredentialUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetLastUsed sets the "last_used" field.
func (_u *WebAuthnCredentialUpdateOne) SetLastUsed(v time.Time) *WebAuthnCredentialUpdateOne {
	_u.mutation.SetLastUsed(v)
	return _u
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (_u *WebAuthnCredentialUpdateOne) SetNillableLastUsed(v *time.Time) *WebAuthnCredentialUpdateOne {
	if v != nil {
		_u.SetLastUsed(*v)
	}
	return _u
}

// ClearLastUsed clears the value of the "last_used" field.
func (_u *WebAuthnCredentialUpdateOne) ClearLastUsed() *WebAuthnCredentialUpdateOne {
	_u.mutation.ClearLastUsed()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *WebAuthnCredentialUpdateOne) SetUserID(id int) *WebAuthnCredentialUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WebAuthnCredentialUpdateOne) SetUser(v *User) *WebAuthnCredentialUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WebAuthnCredentialMutation object of the builder.
func (_u *WebAuthnCredentialUpdateOne) Mutation() *WebAuthnCredentialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WebAuthnCredentialUpdateOne) ClearUser() *WebAuthnCredentialUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the WebAuthnCredentialUpdate builder.
func (_u *WebAuthnCredentialUpdateOne) Where(ps ...predicate.WebAuthnCredential) *WebAuthnCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebAuthnCredentialUpdateOne) Select(field string, fields ...string) *WebAuthnCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WebAuthnCredential entity.
func (_u *WebAuthnCredentialUpdateOne) Save(ctx context.Context) (*WebAuthnCredential, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebAuthnCredentialUpdateOne) SaveX(ctx context.Context) *WebAuthnCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebAuthnCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebAuthnCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebAuthnCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.CredentialID(); ok {
		if err := webauthncredential.CredentialIDValidator(v); err != nil {
			return &ValidationError{Name: "credential_id", err: fmt.Errorf(`ent: validator failed for field "WebAuthnCredential.credential_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Data(); ok {
		if err := webauthncredential.DataValidator(v); err != nil {
			return &ValidationError{Name: "data", err: fmt.Errorf(`ent: validator failed for field "WebAuthnCredential.data": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebAuthnCredential.user"`)
	}
	return nil
}

func (_u *WebAuthnCredentialUpdateOne) sqlSave(ctx context.Context) (_node *WebAuthnCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webauthncredential.Table, webauthncredential.Columns, sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebAuthnCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webauthncredential.FieldID)
		for _, f := range fields {
			if !webauthncredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webauthncredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(webauthncredential.FieldCredentialID, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(webauthncredential.FieldData, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(webauthncredential.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(webauthncredential.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.LastUsed(); ok {
		_spec.SetField(webauthncredential.FieldLastUsed, field.TypeTime, value)
	}
	if _u.mutation.LastUsedCleared() {
		_spec.ClearField(webauthncredential.FieldLastUsed, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webauthncredential.UserTable,
			Columns: []string{webauthncredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webauthncredential.UserTable,
			Columns: []string{webauthncredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WebAuthnCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webauthncredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
