// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/tenant"
	"naust/daemon/internal/store/ent/webdomain"
	"naust/daemon/internal/store/ent/webrule"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebDomainUpdate is the builder for updating WebDomain entities.
type WebDomainUpdate struct {
	config
	hooks    []Hook
	mutation *WebDomainMutation
}

// Where appends a list predicates to the WebDomainUpdate builder.
func (_u *WebDomainUpdate) Where(ps ...predicate.WebDomain) *WebDomainUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *WebDomainUpdate) SetDomain(v string) *WebDomainUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *WebDomainUpdate) SetNillableDomain(v *string) *WebDomainUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetHsts sets the "hsts" field.
func (_u *WebDomainUpdate) SetHsts(v webdomain.Hsts) *WebDomainUpdate {
	_u.mutation.SetHsts(v)
	return _u
}

// SetNillableHsts sets the "hsts" field if the given value is not nil.
func (_u *WebDomainUpdate) SetNillableHsts(v *webdomain.Hsts) *WebDomainUpdate {
	if v != nil {
		_u.SetHsts(*v)
	}
	return _u
}

// SetServeStatic sets the "serve_static" field.
func (_u *WebDomainUpdate) SetServeStatic(v bool) *WebDomainUpdate {
	_u.mutation.SetServeStatic(v)
	return _u
}

// SetNillableServeStatic sets the "serve_static" field if the given value is not nil.
func (_u *WebDomainUpdate) SetNillableServeStatic(v *bool) *WebDomainUpdate {
	if v != nil {
		_u.SetServeStatic(*v)
	}
	return _u
}

// AddRuleIDs adds the "rules" edge to the WebRule entity by IDs.
func (_u *WebDomainUpdate) AddRuleIDs(ids ...int) *WebDomainUpdate {
	_u.mutation.AddRuleIDs(ids...)
	return _u
}

// AddRules adds the "rules" edges to the WebRule entity.
func (_u *WebDomainUpdate) AddRules(v ...*WebRule) *WebDomainUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleIDs(ids...)
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *WebDomainUpdate) SetTenantID(id int) *WebDomainUpdate {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *WebDomainUpdate) SetTenant(v *Tenant) *WebDomainUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the WebDomainMutation object of the builder.
func (_u *WebDomainUpdate) Mutation() *WebDomainMutation {
	return _u.mutation
}

// ClearRules clears all "rules" edges to the WebRule entity.
func (_u *WebDomainUpdate) ClearRules() *WebDomainUpdate {
	_u.mutation.ClearRules()
	return _u
}

// RemoveRuleIDs removes the "rules" edge to WebRule entities by IDs.
func (_u *WebDomainUpdate) RemoveRuleIDs(ids ...int) *WebDomainUpdate {
	_u.mutation.RemoveRuleIDs(ids...)
	return _u
}

// RemoveRules removes "rules" edges to WebRule entities.
func (_u *WebDomainUpdate) RemoveRules(v ...*WebRule) *WebDomainUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleIDs(ids...)
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *WebDomainUpdate) ClearTenant() *WebDomainUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebDomainUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebDomainUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebDomainUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebDomainUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebDomainUpdate) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := webdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "WebDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hsts(); ok {
		if err := webdomain.HstsValidator(v); err != nil {
			return &ValidationError{Name: "hsts", err: fmt.Errorf(`ent: validator failed for field "WebDomain.hsts": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebDomain.tenant"`)
	}
	return nil
}

func (_u *WebDomainUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webdomain.Table, webdomain.Columns, sqlgraph.NewFieldSpec(webdomain.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(webdomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hsts(); ok {
		_spec.SetField(webdomain.FieldHsts, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ServeStatic(); ok {
		_spec.SetField(webdomain.FieldServeStatic, field.TypeBool, value)
	}
	if _u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   webdomain.RulesTable,
			Columns: []string{webdomain.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRulesIDs(); len(nodes) > 0 && !_u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   webdomain.RulesTable,
			Columns: []string{webdomain.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   webdomain.RulesTable,
			Columns: []string{webdomain.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webdomain.TenantTable,
			Columns: []string{webdomain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webdomain.TenantTable,
			Columns: []string{webdomain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebDomainUpdateOne is the builder for updating a single WebDomain entity.
type WebDomainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebDomainMutation
}

// SetDomain sets the "domain" field.
func (_u *WebDomainUpdateOne) SetDomain(v string) *WebDomainUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *WebDomainUpdateOne) SetNillableDomain(v *string) *WebDomainUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetHsts sets the "hsts" field.
func (_u *WebDomainUpdateOne) SetHsts(v webdomain.Hsts) *WebDomainUpdateOne {
	_u.mutation.SetHsts(v)
	return _u
}

// SetNillableHsts sets the "hsts" field if the given value is not nil.
func (_u *WebDomainUpdateOne) SetNillableHsts(v *webdomain.Hsts) *WebDomainUpdateOne {
	if v != nil {
		_u.SetHsts(*v)
	}
	return _u
}

// SetServeStatic sets the "serve_static" field.
func (_u *WebDomainUpdateOne) SetServeStatic(v bool) *WebDomainUpdateOne {
	_u.mutation.SetServeStatic(v)
	return _u
}

// SetNillableServeStatic sets the "serve_static" field if the given value is not nil.
func (_u *WebDomainUpdateOne) SetNillableServeStatic(v *bool) *WebDomainUpdateOne {
	if v != nil {
		_u.SetServeStatic(*v)
	}
	return _u
}

// AddRuleIDs adds the "rules" edge to the WebRule entity by IDs.
func (_u *WebDomainUpdateOne) AddRuleIDs(ids ...int) *WebDomainUpdateOne {
	_u.mutation.AddRuleIDs(ids...)
	return _u
}

// AddRules adds the "rules" edges to the WebRule entity.
func (_u *WebDomainUpdateOne) AddRules(v ...*WebRule) *WebDomainUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleIDs(ids...)
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *WebDomainUpdateOne) SetTenantID(id int) *WebDomainUpdateOne {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *WebDomainUpdateOne) SetTenant(v *Tenant) *WebDomainUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the WebDomainMutation object of the builder.
func (_u *WebDomainUpdateOne) Mutation() *WebDomainMutation {
	return _u.mutation
}

// ClearRules clears all "rules" edges to the WebRule entity.
func (_u *WebDomainUpdateOne) ClearRules() *WebDomainUpdateOne {
	_u.mutation.ClearRules()
	return _u
}

// RemoveRuleIDs removes the "rules" edge to WebRule entities by IDs.
func (_u *WebDomainUpdateOne) RemoveRuleIDs(ids ...int) *WebDomainUpdateOne {
	_u.mutation.RemoveRuleIDs(ids...)
	return _u
}

// RemoveRules removes "rules" edges to WebRule entities.
func (_u *WebDomainUpdateOne) RemoveRules(v ...*WebRule) *WebDomainUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleIDs(ids...)
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *WebDomainUpdateOne) ClearTenant() *WebDomainUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the WebDomainUpdate builder.
func (_u *WebDomainUpdateOne) Where(ps ...predicate.WebDomain) *WebDomainUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebDomainUpdateOne) Select(field string, fields ...string) *WebDomainUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WebDomain entity.
func (_u *WebDomainUpdateOne) Save(ctx context.Context) (*WebDomain, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebDomainUpdateOne) SaveX(ctx context.Context) *WebDomain {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebDomainUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebDomainUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebDomainUpdateOne) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := webdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "WebDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hsts(); ok {
		if err := webdomain.HstsValidator(v); err != nil {
			return &ValidationError{Name: "hsts", err: fmt.Errorf(`ent: validator failed for field "WebDomain.hsts": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebDomain.tenant"`)
	}
	return nil
}

func (_u *WebDomainUpdateOne) sqlSave(ctx context.Context) (_node *WebDomain, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webdomain.Table, webdomain.Columns, sqlgraph.NewFieldSpec(webdomain.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebDomain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webdomain.FieldID)
		for _, f := range fields {
			if !webdomain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webdomain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(webdomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hsts(); ok {
		_spec.SetField(webdomain.FieldHsts, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ServeStatic(); ok {
		_spec.SetField(webdomain.FieldServeStatic, field.TypeBool, value)
	}
	if _u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   webdomain.RulesTable,
			Columns: []string{webdomain.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRulesIDs(); len(nodes) > 0 && !_u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   webdomain.RulesTable,
			Columns: []string{webdomain.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   webdomain.RulesTable,
			Columns: []string{webdomain.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webdomain.TenantTable,
			Columns: []string{webdomain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webdomain.TenantTable,
			Columns: []string{webdomain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WebDomain{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
