// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/tenant"
	"naust/daemon/internal/store/ent/webdomain"
	"naust/daemon/internal/store/ent/webrule"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebDomainCreate is the builder for creating a WebDomain entity.
type WebDomainCreate struct {
	config
	mutation *WebDomainMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDomain sets the "domain" field.
func (_c *WebDomainCreate) SetDomain(v string) *WebDomainCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetHsts sets the "hsts" field.
func (_c *WebDomainCreate) SetHsts(v webdomain.Hsts) *WebDomainCreate {
	_c.mutation.SetHsts(v)
	return _c
}

// SetNillableHsts sets the "hsts" field if the given value is not nil.
func (_c *WebDomainCreate) SetNillableHsts(v *webdomain.Hsts) *WebDomainCreate {
	if v != nil {
		_c.SetHsts(*v)
	}
	return _c
}

// SetServeStatic sets the "serve_static" field.
func (_c *WebDomainCreate) SetServeStatic(v bool) *WebDomainCreate {
	_c.mutation.SetServeStatic(v)
	return _c
}

// SetNillableServeStatic sets the "serve_static" field if the given value is not nil.
func (_c *WebDomainCreate) SetNillableServeStatic(v *bool) *WebDomainCreate {
	if v != nil {
		_c.SetServeStatic(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebDomainCreate) SetCreatedAt(v time.Time) *WebDomainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebDomainCreate) SetNillableCreatedAt(v *time.Time) *WebDomainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// AddRuleIDs adds the "rules" edge to the WebRule entity by IDs.
func (_c *WebDomainCreate) AddRuleIDs(ids ...int) *WebDomainCreate {
	_c.mutation.AddRuleIDs(ids...)
	return _c
}

// AddRules adds the "rules" edges to the WebRule entity.
func (_c *WebDomainCreate) AddRules(v ...*WebRule) *WebDomainCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRuleIDs(ids...)
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_c *WebDomainCreate) SetTenantID(id int) *WebDomainCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *WebDomainCreate) SetTenant(v *Tenant) *WebDomainCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the WebDomainMutation object of the builder.
func (_c *WebDomainCreate) Mutation() *WebDomainMutation {
	return _c.mutation
}

// Save creates the WebDomain in the database.
func (_c *WebDomainCreate) Save(ctx context.Context) (*WebDomain, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebDomainCreate) SaveX(ctx context.Context) *WebDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebDomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebDomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebDomainCreate) defaults() {
	if _, ok := _c.mutation.Hsts(); !ok {
		v := webdomain.DefaultHsts
		_c.mutation.SetHsts(v)
	}
	if _, ok := _c.mutation.ServeStatic(); !ok {
		v := webdomain.DefaultServeStatic
		_c.mutation.SetServeStatic(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webdomain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebDomainCreate) check() error {
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "WebDomain.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := webdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "WebDomain.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hsts(); !ok {
		return &ValidationError{Name: "hsts", err: errors.New(`ent: missing required field "WebDomain.hsts"`)}
	}
	if v, ok := _c.mutation.Hsts(); ok {
		if err := webdomain.HstsValidator(v); err != nil {
			return &ValidationError{Name: "hsts", err: fmt.Errorf(`ent: validator failed for field "WebDomain.hsts": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServeStatic(); !ok {
		return &ValidationError{Name: "serve_static", err: errors.New(`ent: missing required field "WebDomain.serve_static"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebDomain.created_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "WebDomain.tenant"`)}
	}
	return nil
}

func (_c *WebDomainCreate) sqlSave(ctx context.Context) (*WebDomain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebDomainCreate) createSpec() (*WebDomain, *sqlgraph.CreateSpec) {
	var (
		_node = &WebDomain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webdomain.Table, sqlgraph.NewFieldSpec(webdomain.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(webdomain.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Hsts(); ok {
		_spec.SetField(webdomain.FieldHsts, field.TypeEnum, value)
		_node.Hsts = value
	}
	if value, ok := _c.mutation.ServeStatic(); ok {
		_spec.SetField(webdomain.FieldServeStatic, field.TypeBool, value)
		_node.ServeStatic = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webdomain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   webdomain.RulesTable,
			Columns: []string{webdomain.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webdomain.TenantTable,
			Columns: []string{webdomain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_web_domains = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebDomain.Create().
//		SetDomain(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebDomainUpsert) {
//			SetDomain(v+v).
//		}).
//		Exec(ctx)
func (_c *WebDomainCreate) OnConflict(opts ...sql.ConflictOption) *WebDomainUpsertOne {
	_c.conflict = opts
	return &WebDomainUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebDomain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebDomainCreate) OnConflictColumns(columns ...string) *WebDomainUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebDomainUpsertOne{
		create: _c,
	}
}

type (
	// WebDomainUpsertOne is the builder for "upsert"-ing
	//  one WebDomain node.
	WebDomainUpsertOne struct {
		create *WebDomainCreate
	}

	// WebDomainUpsert is the "OnConflict" setter.
	WebDomainUpsert struct {
		*sql.UpdateSet
	}
)

// SetDomain sets the "domain" field.
func (u *WebDomainUpsert) SetDomain(v string) *WebDomainUpsert {
	u.Set(webdomain.FieldDomain, v)
	return u
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *WebDomainUpsert) UpdateDomain() *WebDomainUpsert {
	u.SetExcluded(webdomain.FieldDomain)
	return u
}

// SetHsts sets the "hsts" field.
func (u *WebDomainUpsert) SetHsts(v webdomain.Hsts) *WebDomainUpsert {
	u.Set(webdomain.FieldHsts, v)
	return u
}

// UpdateHsts sets the "hsts" field to the value that was provided on create.
func (u *WebDomainUpsert) UpdateHsts() *WebDomainUpsert {
	u.SetExcluded(webdomain.FieldHsts)
	return u
}

// SetServeStatic sets the "serve_static" field.
func (u *WebDomainUpsert) SetServeStatic(v bool) *WebDomainUpsert {
	u.Set(webdomain.FieldServeStatic, v)
	return u
}

// UpdateServeStatic sets the "serve_static" field to the value that was provided on create.
func (u *WebDomainUpsert) UpdateServeStatic() *WebDomainUpsert {
	u.SetExcluded(webdomain.FieldServeStatic)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WebDomain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebDomainUpsertOne) UpdateNewValues() *WebDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(webdomain.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebDomain.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WebDomainUpsertOne) Ignore() *WebDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebDomainUpsertOne) DoNothing() *WebDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebDomainCreate.OnConflict
// documentation for more info.
func (u *WebDomainUpsertOne) Update(set func(*WebDomainUpsert)) *WebDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebDomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetDomain sets the "domain" field.
func (u *WebDomainUpsertOne) SetDomain(v string) *WebDomainUpsertOne {
	return u.Update(func(s *WebDomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *WebDomainUpsertOne) UpdateDomain() *WebDomainUpsertOne {
	return u.Update(func(s *WebDomainUpsert) {
		s.UpdateDomain()
	})
}

// SetHsts sets the "hsts" field.
func (u *WebDomainUpsertOne) SetHsts(v webdomain.Hsts) *WebDomainUpsertOne {
	return u.Update(func(s *WebDomainUpsert) {
		s.SetHsts(v)
	})
}

// UpdateHsts sets the "hsts" field to the value that was provided on create.
func (u *WebDomainUpsertOne) UpdateHsts() *WebDomainUpsertOne {
	return u.Update(func(s *WebDomainUpsert) {
		s.UpdateHsts()
	})
}

// SetServeStatic sets the "serve_static" field.
func (u *WebDomainUpsertOne) SetServeStatic(v bool) *WebDomainUpsertOne {
	return u.Update(func(s *WebDomainUpsert) {
		s.SetServeStatic(v)
	})
}

// UpdateServeStatic sets the "serve_static" field to the value that was provided on create.
func (u *WebDomainUpsertOne) UpdateServeStatic() *WebDomainUpsertOne {
	return u.Update(func(s *WebDomainUpsert) {
		s.UpdateServeStatic()
	})
}

// Exec executes the query.
func (u *WebDomainUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebDomainCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebDomainUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WebDomainUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WebDomainUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WebDomainCreateBulk is the builder for creating many WebDomain entities in bulk.
type WebDomainCreateBulk struct {
	config
	err      error
	builders []*WebDomainCreate
	conflict []sql.ConflictOption
}

// Save creates the WebDomain entities in the database.
func (_c *WebDomainCreateBulk) Save(ctx context.Context) ([]*WebDomain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebDomain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebDomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebDomainCreateBulk) SaveX(ctx context.Context) []*WebDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebDomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebDomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebDomain.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebDomainUpsert) {
//			SetDomain(v+v).
//		}).
//		Exec(ctx)
func (_c *WebDomainCreateBulk) OnConflict(opts ...sql.ConflictOption) *WebDomainUpsertBulk {
	_c.conflict = opts
	return &WebDomainUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebDomain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebDomainCreateBulk) OnConflictColumns(columns ...string) *WebDomainUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebDomainUpsertBulk{
		create: _c,
	}
}

// WebDomainUpsertBulk is the builder for "upsert"-ing
// a bulk of WebDomain nodes.
type WebDomainUpsertBulk struct {
	create *WebDomainCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WebDomain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebDomainUpsertBulk) UpdateNewValues() *WebDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(webdomain.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebDomain.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WebDomainUpsertBulk) Ignore() *WebDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebDomainUpsertBulk) DoNothing() *WebDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebDomainCreateBulk.OnConflict
// documentation for more info.
func (u *WebDomainUpsertBulk) Update(set func(*WebDomainUpsert)) *WebDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebDomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetDomain sets the "domain" field.
func (u *WebDomainUpsertBulk) SetDomain(v string) *WebDomainUpsertBulk {
	return u.Update(func(s *WebDomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *WebDomainUpsertBulk) UpdateDomain() *WebDomainUpsertBulk {
	return u.Update(func(s *WebDomainUpsert) {
		s.UpdateDomain()
	})
}

// SetHsts sets the "hsts" field.
func (u *WebDomainUpsertBulk) SetHsts(v webdomain.Hsts) *WebDomainUpsertBulk {
	return u.Update(func(s *WebDomainUpsert) {
		s.SetHsts(v)
	})
}

// UpdateHsts sets the "hsts" field to the value that was provided on create.
func (u *WebDomainUpsertBulk) UpdateHsts() *WebDomainUpsertBulk {
	return u.Update(func(s *WebDomainUpsert) {
		s.UpdateHsts()
	})
}

// SetServeStatic sets the "serve_static" field.
func (u *WebDomainUpsertBulk) SetServeStatic(v bool) *WebDomainUpsertBulk {
	return u.Update(func(s *WebDomainUpsert) {
		s.SetServeStatic(v)
	})
}

// UpdateServeStatic sets the "serve_static" field to the value that was provided on create.
func (u *WebDomainUpsertBulk) UpdateServeStatic() *WebDomainUpsertBulk {
	return u.Update(func(s *WebDomainUpsert) {
		s.UpdateServeStatic()
	})
}

// Exec executes the query.
func (u *WebDomainUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WebDomainCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebDomainCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebDomainUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
