// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/webdomain"
	"naust/daemon/internal/store/ent/webrule"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebRuleUpdate is the builder for updating WebRule entities.
type WebRuleUpdate struct {
	config
	hooks    []Hook
	mutation *WebRuleMutation
}

// Where appends a list predicates to the WebRuleUpdate builder.
func (_u *WebRuleUpdate) Where(ps ...predicate.WebRule) *WebRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *WebRuleUpdate) SetKind(v webrule.Kind) *WebRuleUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *WebRuleUpdate) SetNillableKind(v *webrule.Kind) *WebRuleUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *WebRuleUpdate) SetPath(v string) *WebRuleUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *WebRuleUpdate) SetNillablePath(v *string) *WebRuleUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *WebRuleUpdate) SetTarget(v string) *WebRuleUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *WebRuleUpdate) SetNillableTarget(v *string) *WebRuleUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetPassHostHeader sets the "pass_host_header" field.
func (_u *WebRuleUpdate) SetPassHostHeader(v bool) *WebRuleUpdate {
	_u.mutation.SetPassHostHeader(v)
	return _u
}

// SetNillablePassHostHeader sets the "pass_host_header" field if the given value is not nil.
func (_u *WebRuleUpdate) SetNillablePassHostHeader(v *bool) *WebRuleUpdate {
	if v != nil {
		_u.SetPassHostHeader(*v)
	}
	return _u
}

// SetNoProxyRedirect sets the "no_proxy_redirect" field.
func (_u *WebRuleUpdate) SetNoProxyRedirect(v bool) *WebRuleUpdate {
	_u.mutation.SetNoProxyRedirect(v)
	return _u
}

// SetNillableNoProxyRedirect sets the "no_proxy_redirect" field if the given value is not nil.
func (_u *WebRuleUpdate) SetNillableNoProxyRedirect(v *bool) *WebRuleUpdate {
	if v != nil {
		_u.SetNoProxyRedirect(*v)
	}
	return _u
}

// SetFrameSameOrigin sets the "frame_same_origin" field.
func (_u *WebRuleUpdate) SetFrameSameOrigin(v bool) *WebRuleUpdate {
	_u.mutation.SetFrameSameOrigin(v)
	return _u
}

// SetNillableFrameSameOrigin sets the "frame_same_origin" field if the given value is not nil.
func (_u *WebRuleUpdate) SetNillableFrameSameOrigin(v *bool) *WebRuleUpdate {
	if v != nil {
		_u.SetFrameSameOrigin(*v)
	}
	return _u
}

// SetWebSockets sets the "web_sockets" field.
func (_u *WebRuleUpdate) SetWebSockets(v bool) *WebRuleUpdate {
	_u.mutation.SetWebSockets(v)
	return _u
}

// SetNillableWebSockets sets the "web_sockets" field if the given value is not nil.
func (_u *WebRuleUpdate) SetNillableWebSockets(v *bool) *WebRuleUpdate {
	if v != nil {
		_u.SetWebSockets(*v)
	}
	return _u
}

// SetDomainID sets the "domain" edge to the WebDomain entity by ID.
func (_u *WebRuleUpdate) SetDomainID(id int) *WebRuleUpdate {
	_u.mutation.SetDomainID(id)
	return _u
}

// SetDomain sets the "domain" edge to the WebDomain entity.
func (_u *WebRuleUpdate) SetDomain(v *WebDomain) *WebRuleUpdate {
	return _u.SetDomainID(v.ID)
}

// Mutation returns the WebRuleMutation object of the builder.
func (_u *WebRuleUpdate) Mutation() *WebRuleMutation {
	return _u.mutation
}

// ClearDomain clears the "domain" edge to the WebDomain entity.
func (_u *WebRuleUpdate) ClearDomain() *WebRuleUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebRuleUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := webrule.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "WebRule.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := webrule.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "WebRule.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Target(); ok {
		if err := webrule.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "WebRule.target": %w`, err)}
		}
	}
	if _u.mutation.DomainCleared() && len(_u.mutation.DomainIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebRule.domain"`)
	}
	return nil
}

func (_u *WebRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webrule.Table, webrule.Columns, sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(webrule.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(webrule.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(webrule.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassHostHeader(); ok {
		_spec.SetField(webrule.FieldPassHostHeader, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NoProxyRedirect(); ok {
		_spec.SetField(webrule.FieldNoProxyRedirect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FrameSameOrigin(); ok {
		_spec.SetField(webrule.FieldFrameSameOrigin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebSockets(); ok {
		_spec.SetField(webrule.FieldWebSockets, field.TypeBool, value)
	}
	if _u.mutation.DomainCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webrule.DomainTable,
			Columns: []string{webrule.DomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webdomain.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webrule.DomainTable,
			Columns: []string{webrule.DomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webdomain.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebRuleUpdateOne is the builder for updating a single WebRule entity.
type WebRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebRuleMutation
}

// SetKind sets the "kind" field.
func (_u *WebRuleUpdateOne) SetKind(v webrule.Kind) *WebRuleUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *WebRuleUpdateOne) SetNillableKind(v *webrule.Kind) *WebRuleUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *WebRuleUpdateOne) SetPath(v string) *WebRuleUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *WebRuleUpdateOne) SetNillablePath(v *string) *WebRuleUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *WebRuleUpdateOne) SetTarget(v string) *WebRuleUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *WebRuleUpdateOne) SetNillableTarget(v *string) *WebRuleUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetPassHostHeader sets the "pass_host_header" field.
func (_u *WebRuleUpdateOne) SetPassHostHeader(v bool) *WebRuleUpdateOne {
	_u.mutation.SetPassHostHeader(v)
	return _u
}

// SetNillablePassHostHeader sets the "pass_host_header" field if the given value is not nil.
func (_u *WebRuleUpdateOne) SetNillablePassHostHeader(v *bool) *WebRuleUpdateOne {
	if v != nil {
		_u.SetPassHostHeader(*v)
	}
	return _u
}

// SetNoProxyRedirect sets the "no_proxy_redirect" field.
func (_u *WebRuleUpdateOne) SetNoProxyRedirect(v bool) *WebRuleUpdateOne {
	_u.mutation.SetNoProxyRedirect(v)
	return _u
}

// SetNillableNoProxyRedirect sets the "no_proxy_redirect" field if the given value is not nil.
func (_u *WebRuleUpdateOne) SetNillableNoProxyRedirect(v *bool) *WebRuleUpdateOne {
	if v != nil {
		_u.SetNoProxyRedirect(*v)
	}
	return _u
}

// SetFrameSameOrigin sets the "frame_same_origin" field.
func (_u *WebRuleUpdateOne) SetFrameSameOrigin(v bool) *WebRuleUpdateOne {
	_u.mutation.SetFrameSameOrigin(v)
	return _u
}

// SetNillableFrameSameOrigin sets the "frame_same_origin" field if the given value is not nil.
func (_u *WebRuleUpdateOne) SetNillableFrameSameOrigin(v *bool) *WebRuleUpdateOne {
	if v != nil {
		_u.SetFrameSameOrigin(*v)
	}
	return _u
}

// SetWebSockets sets the "web_sockets" field.
func (_u *WebRuleUpdateOne) SetWebSockets(v bool) *WebRuleUpdateOne {
	_u.mutation.SetWebSockets(v)
	return _u
}

// SetNillableWebSockets sets the "web_sockets" field if the given value is not nil.
func (_u *WebRuleUpdateOne) SetNillableWebSockets(v *bool) *WebRuleUpdateOne {
	if v != nil {
		_u.SetWebSockets(*v)
	}
	return _u
}

// SetDomainID sets the "domain" edge to the WebDomain entity by ID.
func (_u *WebRuleUpdateOne) SetDomainID(id int) *WebRuleUpdateOne {
	_u.mutation.SetDomainID(id)
	return _u
}

// SetDomain sets the "domain" edge to the WebDomain entity.
func (_u *WebRuleUpdateOne) SetDomain(v *WebDomain) *WebRuleUpdateOne {
	return _u.SetDomainID(v.ID)
}

// Mutation returns the WebRuleMutation object of the builder.
func (_u *WebRuleUpdateOne) Mutation() *WebRuleMutation {
	return _u.mutation
}

// ClearDomain clears the "domain" edge to the WebDomain entity.
func (_u *WebRuleUpdateOne) ClearDomain() *WebRuleUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// Where appends a list predicates to the WebRuleUpdate builder.
func (_u *WebRuleUpdateOne) Where(ps ...predicate.WebRule) *WebRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebRuleUpdateOne) Select(field string, fields ...string) *WebRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WebRule entity.
func (_u *WebRuleUpdateOne) Save(ctx context.Context) (*WebRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebRuleUpdateOne) SaveX(ctx context.Context) *WebRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := webrule.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "WebRule.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := webrule.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "WebRule.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Target(); ok {
		if err := webrule.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "WebRule.target": %w`, err)}
		}
	}
	if _u.mutation.DomainCleared() && len(_u.mutation.DomainIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebRule.domain"`)
	}
	return nil
}

func (_u *WebRuleUpdateOne) sqlSave(ctx context.Context) (_node *WebRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webrule.Table, webrule.Columns, sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webrule.FieldID)
		for _, f := range fields {
			if !webrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(webrule.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(webrule.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(webrule.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassHostHeader(); ok {
		_spec.SetField(webrule.FieldPassHostHeader, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NoProxyRedirect(); ok {
		_spec.SetField(webrule.FieldNoProxyRedirect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FrameSameOrigin(); ok {
		_spec.SetField(webrule.FieldFrameSameOrigin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebSockets(); ok {
		_spec.SetField(webrule.FieldWebSockets, field.TypeBool, value)
	}
	if _u.mutation.DomainCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webrule.DomainTable,
			Columns: []string{webrule.DomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webdomain.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webrule.DomainTable,
			Columns: []string{webrule.DomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webdomain.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WebRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
